#!/usr/bin/env python3
"""Emit Pelmet/Resources/Localizable.xcstrings from the table below.

Source of truth for translations. Edit a string here, re-run, commit both.
English keys must match the literals in code byte-for-byte (dashes, ellipses,
newlines). Interpolations use `%@`. Xcode's String Catalog editor can still
open the output; hand-edits there get overwritten by this script, so keep
edits here.
"""

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "Pelmet" / "Resources" / "Localizable.xcstrings"

# key -> {lang: translation}
T = {
    # ── Settings shell ──────────────────────────────────────────────
    "General": dict(de="Allgemein", fr="Général", es="General", it="Generali", pt="Geral", ja="一般", zh="通用", ko="일반", ru="Основные"),
    "Behavior": dict(de="Verhalten", fr="Comportement", es="Comportamiento", it="Comportamento", pt="Comportamento", ja="動作", zh="行为", ko="동작", ru="Поведение"),
    "Menu Bar": dict(de="Menüleiste", fr="Barre des menus", es="Barra de menús", it="Barra dei menu", pt="Barra de menus", ja="メニューバー", zh="菜单栏", ko="메뉴 막대", ru="Строка меню"),
    "Displays": dict(de="Displays", fr="Écrans", es="Pantallas", it="Schermi", pt="Telas", ja="ディスプレイ", zh="显示器", ko="디스플레이", ru="Мониторы"),
    "About": dict(de="Über", fr="À propos", es="Acerca de", it="Informazioni", pt="Sobre", ja="情報", zh="关于", ko="정보", ru="О программе"),
    "Pelmet Settings": dict(de="Pelmet-Einstellungen", fr="Réglages de Pelmet", es="Ajustes de Pelmet", it="Impostazioni di Pelmet", pt="Ajustes do Pelmet", ja="Pelmet設定", zh="Pelmet 设置", ko="Pelmet 설정", ru="Настройки Pelmet"),

    # ── Thanks pane ─────────────────────────────────────────────────
    "Thanks": dict(de="Danke", fr="Merci", es="Gracias", it="Grazie", pt="Obrigado", ja="ありがとう", zh="感谢", ko="감사", ru="Спасибо"),
    "Pelmet is free. It stays that way.": dict(de="Pelmet ist kostenlos. Und bleibt es.", fr="Pelmet est gratuit. Et le restera.", es="Pelmet es gratis. Y seguirá siéndolo.", it="Pelmet è gratuito. E lo resterà.", pt="O Pelmet é gratuito. E vai continuar assim.", ja="Pelmetは無料です。これからもずっと。", zh="Pelmet 免费，并将一直免费。", ko="Pelmet은 무료입니다. 앞으로도 그렇습니다.", ru="Pelmet бесплатен. И останется таким."),
    "One person builds it on evenings and weekends. No account, no tracking, no upsell.\nIf it earned a spot in your bar, here's how to help.": dict(
        de="Eine Person baut es abends und am Wochenende. Kein Konto, kein Tracking, kein Upselling.\nWenn es sich einen Platz in deiner Leiste verdient hat, kannst du so helfen.",
        fr="Une seule personne le développe le soir et le week-end. Pas de compte, pas de suivi, pas de vente forcée.\nS’il a mérité sa place dans votre barre, voici comment aider.",
        es="Una sola persona lo desarrolla por las tardes y los fines de semana. Sin cuenta, sin rastreo, sin ventas adicionales.\nSi se ha ganado un sitio en tu barra, así puedes ayudar.",
        it="Una sola persona lo sviluppa la sera e nei fine settimana. Nessun account, nessun tracciamento, nessun upselling.\nSe si è guadagnato un posto nella tua barra, ecco come aiutare.",
        pt="Uma só pessoa o desenvolve à noite e nos fins de semana. Sem conta, sem rastreamento, sem venda adicional.\nSe ele conquistou um lugar na sua barra, veja como ajudar.",
        ja="一人で夜と週末に開発しています。アカウント不要、トラッキングなし、アップセルなし。\nあなたのバーに居場所を得られたなら、こんな形で応援できます。",
        zh="一个人利用晚上和周末开发了它。无需账户，不追踪，不推销。\n如果它在你的菜单栏中赢得了一席之地，可以这样支持。",
        ko="한 사람이 저녁과 주말에 만들고 있습니다. 계정도, 추적도, 유료 유도도 없습니다.\n메뉴 막대에 자리를 얻었다면 이렇게 도울 수 있습니다.",
        ru="Его делает один человек по вечерам и выходным. Без аккаунта, без слежки, без навязчивых продаж.\nЕсли он заслужил место в вашей строке меню, вот как помочь."),
    "Sponsor on GitHub": dict(de="Auf GitHub sponsern", fr="Sponsoriser sur GitHub", es="Patrocinar en GitHub", it="Sponsorizza su GitHub", pt="Patrocinar no GitHub", ja="GitHubでスポンサーになる", zh="在 GitHub 上赞助", ko="GitHub에서 후원하기", ru="Поддержать на GitHub"),
    "From a coffee a month. Keeps the releases coming.": dict(de="Ab einem Kaffee im Monat. Hält die Updates am Laufen.", fr="À partir d’un café par mois. Ça fait vivre les mises à jour.", es="Desde un café al mes. Mantiene las actualizaciones en marcha.", it="Da un caffè al mese. Tiene in vita gli aggiornamenti.", pt="A partir de um café por mês. Mantém as atualizações vindo.", ja="月にコーヒー1杯分から。アップデートを続ける力になります。", zh="每月一杯咖啡起。让更新持续下去。", ko="한 달에 커피 한 잔부터. 업데이트를 이어가게 합니다.", ru="От чашки кофе в месяц. Так обновления продолжают выходить."),
    "A star helps more people find Pelmet.": dict(de="Ein Stern hilft mehr Leuten, Pelmet zu finden.", fr="Une étoile aide plus de gens à trouver Pelmet.", es="Una estrella ayuda a que más gente encuentre Pelmet.", it="Una stella aiuta più persone a trovare Pelmet.", pt="Uma estrela ajuda mais pessoas a encontrar o Pelmet.", ja="スターが、より多くの人にPelmetを届けます。", zh="一颗星能让更多人发现 Pelmet。", ko="별 하나가 더 많은 사람이 Pelmet을 찾게 합니다.", ru="Звезда помогает большему числу людей найти Pelmet."),
    "Star on GitHub": dict(de="Auf GitHub markieren", fr="Étoiler sur GitHub", es="Dar una estrella en GitHub", it="Metti una stella su GitHub", pt="Dar estrela no GitHub", ja="GitHubでスターする", zh="在 GitHub 上加星", ko="GitHub에서 별 주기", ru="Поставить звезду на GitHub"),
    "%lld stars": dict(de="%lld Sterne", fr="%lld étoiles", es="%lld estrellas", it="%lld stelle", pt="%lld estrelas", ja="スター %lld", zh="%lld 颗星", ko="별 %lld개", ru="%lld звёзд"),
    "Follow along for releases and what's next.": dict(de="Folge mit für neue Versionen und was als Nächstes kommt.", fr="Suivez les nouveautés et ce qui arrive ensuite.", es="Sigue las novedades y lo que viene después.", it="Segui le novità e ciò che arriverà.", pt="Acompanhe os lançamentos e o que vem por aí.", ja="リリース情報と今後の予定をフォロー。", zh="关注新版本和后续计划。", ko="새 버전과 다음 계획을 팔로우하세요.", ru="Следите за релизами и планами."),
    "Tell a friend": dict(de="Weitersagen", fr="En parler à un ami", es="Contárselo a un amigo", it="Dillo a un amico", pt="Contar a um amigo", ja="友達に教える", zh="推荐给朋友", ko="친구에게 알리기", ru="Рассказать другу"),
    "Enjoy the extra room up there.": dict(de="Genieß den Platz da oben.", fr="Profitez de la place gagnée là-haut.", es="Disfruta del espacio extra ahí arriba.", it="Goditi lo spazio in più lassù.", pt="Aproveite o espaço extra lá em cima.", ja="上の余白を楽しんでください。", zh="享受上面多出来的空间吧。", ko="위쪽에 생긴 여유를 즐기세요.", ru="Наслаждайтесь свободным местом наверху."),
    "Found a bug?": dict(de="Fehler gefunden?", fr="Un bug ?", es="¿Has encontrado un error?", it="Trovato un bug?", pt="Encontrou um bug?", ja="バグを見つけた？", zh="发现了问题？", ko="버그를 찾으셨나요?", ru="Нашли ошибку?"),

    # ── General pane ────────────────────────────────────────────────
    "Launch at login": dict(de="Bei der Anmeldung öffnen", fr="Ouvrir à l’ouverture de session", es="Abrir al iniciar sesión", it="Apri al login", pt="Abrir ao iniciar sessão", ja="ログイン時に起動", zh="登录时启动", ko="로그인 시 열기", ru="Открывать при входе"),
    "Show Pelmet icon in the menu bar": dict(de="Pelmet-Symbol in der Menüleiste anzeigen", fr="Afficher l’icône Pelmet dans la barre des menus", es="Mostrar el icono de Pelmet en la barra de menús", it="Mostra l’icona di Pelmet nella barra dei menu", pt="Mostrar o ícone do Pelmet na barra de menus", ja="メニューバーにPelmetアイコンを表示", zh="在菜单栏中显示 Pelmet 图标", ko="메뉴 막대에 Pelmet 아이콘 표시", ru="Показывать значок Pelmet в строке меню"),
    "Icon": dict(de="Symbol", fr="Icône", es="Icono", it="Icona", pt="Ícone", ja="アイコン", zh="图标", ko="아이콘", ru="Значок"),
    "Without it: press %@, reopen Pelmet from Spotlight, or right-click a separator or empty menu bar spot.": dict(
        de="Ohne Symbol: %@ drücken, Pelmet erneut über Spotlight öffnen oder mit der rechten Maustaste auf einen Trenner oder eine freie Stelle der Menüleiste klicken.",
        fr="Sans elle : appuyez sur %@, rouvrez Pelmet depuis Spotlight, ou faites un clic droit sur un séparateur ou une zone vide de la barre des menus.",
        es="Sin él: pulsa %@, vuelve a abrir Pelmet desde Spotlight, o haz clic derecho en un separador o en un espacio vacío de la barra de menús.",
        it="Senza icona: premi %@, riapri Pelmet da Spotlight, oppure fai clic destro su un separatore o su uno spazio vuoto della barra dei menu.",
        pt="Sem ele: pressione %@, reabra o Pelmet pelo Spotlight, ou clique com o botão direito em um separador ou em um espaço vazio da barra de menus.",
        ja="非表示の場合：%@ を押すか、SpotlightからPelmetを再度開くか、区切りまたはメニューバーの空いている場所を右クリックしてください。",
        zh="隐藏后：可按 %@，通过 Spotlight 重新打开 Pelmet，或右键点击分隔符或菜单栏的空白处。",
        ko="숨기면: %@ 를 누르거나, Spotlight에서 Pelmet을 다시 열거나, 구분선 또는 메뉴 막대의 빈 곳을 오른쪽 클릭하세요.",
        ru="Без значка: нажмите %@, откройте Pelmet через Spotlight или нажмите правой кнопкой на разделитель или пустое место строки меню."),
    "Right-click menu": dict(
        de="Rechtsklick-Menü", fr="Menu du clic droit", es="Menú del clic derecho",
        it="Menu del clic destro", pt="Menu do clique direito", ja="右クリックメニュー",
        zh="右键菜单", ko="오른쪽 클릭 메뉴", ru="Меню по правому клику"),
    "Opens Pelmet's menu from an empty spot on the menu bar.": dict(
        de="Öffnet Pelmets Menü über eine freie Stelle der Menüleiste.",
        fr="Ouvre le menu de Pelmet depuis une zone vide de la barre des menus.",
        es="Abre el menú de Pelmet desde un espacio vacío de la barra de menús.",
        it="Apre il menu di Pelmet da uno spazio vuoto della barra dei menu.",
        pt="Abre o menu do Pelmet a partir de um espaço vazio da barra de menus.",
        ja="メニューバーの空いている場所からPelmetのメニューを開きます。",
        zh="从菜单栏的空白处打开 Pelmet 菜单。",
        ko="메뉴 막대의 빈 곳에서 Pelmet 메뉴를 엽니다.",
        ru="Открывает меню Pelmet с пустого места строки меню."),
    "Stays on while the Pelmet icon is hidden — it's the way back to Settings.": dict(
        de="Bleibt aktiv, solange das Pelmet-Symbol ausgeblendet ist — es ist der Weg zurück zu den Einstellungen.",
        fr="Reste actif tant que l’icône de Pelmet est masquée : c’est le chemin de retour vers les réglages.",
        es="Permanece activo mientras el icono de Pelmet está oculto: es la forma de volver a los ajustes.",
        it="Resta attivo finché l’icona di Pelmet è nascosta: è la via di ritorno alle impostazioni.",
        pt="Continua ativo enquanto o ícone do Pelmet está oculto — é o caminho de volta aos ajustes.",
        ja="Pelmetのアイコンを非表示にしている間は有効のままです。設定に戻る唯一の入口です。",
        zh="在 Pelmet 图标隐藏期间保持开启——这是回到设置的入口。",
        ko="Pelmet 아이콘을 숨긴 동안에는 켜진 상태로 유지됩니다. 설정으로 돌아가는 통로입니다.",
        ru="Остаётся включённым, пока значок Pelmet скрыт, — это путь обратно к настройкам."),
    "Display language": dict(de="Anzeigesprache", fr="Langue d’affichage", es="Idioma de la interfaz", it="Lingua dell’interfaccia", pt="Idioma da interface", ja="表示言語", zh="显示语言", ko="표시 언어", ru="Язык интерфейса"),
    "Language": dict(de="Sprache", fr="Langue", es="Idioma", it="Lingua", pt="Idioma", ja="言語", zh="语言", ko="언어", ru="Язык"),
    "Relaunches Pelmet to apply.": dict(de="Pelmet wird zum Übernehmen neu gestartet.", fr="Pelmet redémarre pour appliquer.", es="Pelmet se reinicia para aplicarlo.", it="Pelmet si riavvia per applicare.", pt="O Pelmet reinicia para aplicar.", ja="適用するにはPelmetが再起動します。", zh="Pelmet 将重新启动以应用。", ko="적용하려면 Pelmet이 다시 실행됩니다.", ru="Pelmet перезапустится, чтобы применить."),
    "System language": dict(de="Systemsprache", fr="Langue du système", es="Idioma del sistema", it="Lingua di sistema", pt="Idioma do sistema", ja="システムの言語", zh="系统语言", ko="시스템 언어", ru="Язык системы"),
    "Relaunch Pelmet to change its language?": dict(de="Pelmet neu starten, um die Sprache zu ändern?", fr="Redémarrer Pelmet pour changer de langue ?", es="¿Reiniciar Pelmet para cambiar el idioma?", it="Riavviare Pelmet per cambiare lingua?", pt="Reiniciar o Pelmet para mudar o idioma?", ja="言語を変更するためにPelmetを再起動しますか？", zh="要重新启动 Pelmet 以更改语言吗？", ko="언어를 변경하기 위해 Pelmet을 다시 실행할까요?", ru="Перезапустить Pelmet, чтобы сменить язык?"),
    "The new language applies the next time Pelmet opens. Your menu bar layout is kept.": dict(de="Die neue Sprache gilt ab dem nächsten Start von Pelmet. Dein Menüleisten-Layout bleibt erhalten.", fr="La nouvelle langue s’applique à la prochaine ouverture de Pelmet. La disposition de votre barre des menus est conservée.", es="El nuevo idioma se aplica la próxima vez que se abra Pelmet. La disposición de tu barra de menús se conserva.", it="La nuova lingua si applica alla prossima apertura di Pelmet. La disposizione della barra dei menu viene conservata.", pt="O novo idioma vale na próxima vez que o Pelmet abrir. A disposição da sua barra de menus é mantida.", ja="新しい言語は次回Pelmetを開いたときに適用されます。メニューバーの配置はそのまま保持されます。", zh="新语言将在下次打开 Pelmet 时生效。菜单栏布局会保留。", ko="새 언어는 다음에 Pelmet을 열 때 적용됩니다. 메뉴 막대 배치는 그대로 유지됩니다.", ru="Новый язык применится при следующем запуске Pelmet. Раскладка строки меню сохранится."),
    "Relaunch Now": dict(de="Jetzt neu starten", fr="Redémarrer maintenant", es="Reiniciar ahora", it="Riavvia ora", pt="Reiniciar agora", ja="今すぐ再起動", zh="立即重新启动", ko="지금 다시 실행", ru="Перезапустить сейчас"),
    "Later": dict(de="Später", fr="Plus tard", es="Más tarde", it="Più tardi", pt="Mais tarde", ja="あとで", zh="稍后", ko="나중에", ru="Позже"),
    "Reveal": dict(de="Einblenden", fr="Affichage", es="Mostrar", it="Mostra", pt="Revelar", ja="表示", zh="显示", ko="표시", ru="Показ"),
    "Rest the pointer on the right half of the menu bar.": dict(de="Zeiger auf der rechten Hälfte der Menüleiste ruhen lassen.", fr="Laisse le pointeur sur la moitié droite de la barre des menus.", es="Deja el puntero sobre la mitad derecha de la barra de menús.", it="Lascia il puntatore sulla metà destra della barra dei menu.", pt="Deixe o ponteiro na metade direita da barra de menus.", ja="メニューバーの右半分にポインタを置きます。", zh="将指针停在菜单栏右半部分。", ko="메뉴 막대 오른쪽 절반에 포인터를 올려 두세요.", ru="Задержите указатель на правой половине строки меню."),
    "Reveal on hover": dict(de="Beim Überfahren einblenden", fr="Afficher au survol", es="Mostrar al pasar el cursor", it="Mostra al passaggio del cursore", pt="Revelar ao passar o cursor", ja="ホバーで表示", zh="悬停时显示", ko="마우스를 올리면 표시", ru="Показывать при наведении"),
    "Hover delay": dict(de="Verzögerung", fr="Délai de survol", es="Retardo", it="Ritardo", pt="Atraso", ja="ホバーの遅延", zh="悬停延迟", ko="지연 시간", ru="Задержка"),
    "Reveal on click in empty menu bar area": dict(de="Bei Klick auf freie Menüleistenfläche einblenden", fr="Afficher au clic dans une zone vide de la barre des menus", es="Mostrar al hacer clic en un área vacía de la barra de menús", it="Mostra al clic su un’area vuota della barra dei menu", pt="Revelar ao clicar em uma área vazia da barra de menus", ja="メニューバーの空いている場所をクリックで表示", zh="点击菜单栏空白处时显示", ko="메뉴 막대 빈 곳을 클릭하면 표시", ru="Показывать при щелчке по пустой области строки меню"),
    "Double-click reveals always-hidden too": dict(de="Doppelklick blendet auch „Immer ausgeblendet“ ein", fr="Le double-clic affiche aussi les éléments toujours masqués", es="El doble clic también muestra los siempre ocultos", it="Il doppio clic mostra anche i sempre nascosti", pt="Clique duplo revela também os sempre ocultos", ja="ダブルクリックで「常に非表示」も表示", zh="双击同时显示“始终隐藏”的图标", ko="더블 클릭 시 항상 숨김 항목도 표시", ru="Двойной щелчок показывает и всегда скрытые"),
    "Instant": dict(de="Sofort", fr="Instantané", es="Instantánea", it="Istantanea", pt="Instantânea", ja="即時", zh="即时", ko="즉시", ru="Мгновенно"),
    "Smooth": dict(de="Sanft", fr="Fluide", es="Suave", it="Fluida", pt="Suave", ja="スムーズ", zh="平滑", ko="부드럽게", ru="Плавно"),
    "Fade": dict(de="Überblenden", fr="Fondu", es="Fundido", it="Dissolvenza", pt="Esmaecer", ja="フェード", zh="淡入淡出", ko="페이드", ru="Затухание"),
    "Auto-rehide": dict(de="Automatisch ausblenden", fr="Masquage automatique", es="Ocultar automáticamente", it="Nascondi automaticamente", pt="Ocultar automaticamente", ja="自動的に隠す", zh="自动重新隐藏", ko="자동 숨김", ru="Автоскрытие"),
    "Automatically rehide": dict(de="Automatisch wieder ausblenden", fr="Masquer à nouveau automatiquement", es="Volver a ocultar automáticamente", it="Nascondi di nuovo automaticamente", pt="Ocultar novamente de forma automática", ja="自動的に再び隠す", zh="自动重新隐藏", ko="자동으로 다시 숨김", ru="Скрывать автоматически"),
    "After": dict(de="Nach", fr="Après", es="Tras", it="Dopo", pt="Após", ja="経過後", zh="延迟", ko="대기 시간", ru="Через"),
    "Rehide when clicking elsewhere": dict(de="Bei Klick an anderer Stelle ausblenden", fr="Masquer en cliquant ailleurs", es="Ocultar al hacer clic en otro sitio", it="Nascondi quando fai clic altrove", pt="Ocultar ao clicar em outro lugar", ja="他の場所をクリックしたら隠す", zh="点击其他位置时隐藏", ko="다른 곳을 클릭하면 숨김", ru="Скрывать при щелчке в другом месте"),
    "System extras": dict(de="System-Extras", fr="Extras système", es="Extras del sistema", it="Extra di sistema", pt="Extras do sistema", ja="システムの追加項目", zh="系统附加项", ko="시스템 추가 항목", ru="Системные элементы"),
    "Now Playing, camera controls, AirDrop, Focus, Timer": dict(de="Jetzt läuft, Kamerasteuerung, AirDrop, Fokus, Timer", fr="Lecture en cours, commandes de caméra, AirDrop, Concentration, Minuteur", es="Ahora suena, controles de cámara, AirDrop, Modos de concentración, Temporizador", it="In riproduzione, controlli fotocamera, AirDrop, Full immersion, Timer", pt="Tocando agora, controles de câmera, AirDrop, Foco, Timer", ja="再生中、カメラコントロール、AirDrop、集中モード、タイマー", zh="现在播放、相机控制、隔空投送、专注模式、计时器", ko="지금 재생 중, 카메라 제어, AirDrop, 집중 모드, 타이머", ru="Сейчас играет, управление камерой, AirDrop, Фокусирование, Таймер"),
    "macOS hides these whenever any icons are concealed — they can only appear while the whole bar is revealed.": dict(
        de="macOS blendet diese aus, sobald irgendein Symbol verborgen ist – sie erscheinen nur, während die gesamte Leiste eingeblendet ist.",
        fr="macOS les masque dès qu’une icône est cachée : ils n’apparaissent que lorsque toute la barre est affichée.",
        es="macOS los oculta siempre que haya algún icono escondido: solo aparecen mientras toda la barra está visible.",
        it="macOS li nasconde ogni volta che un’icona è celata: compaiono solo mentre l’intera barra è visibile.",
        pt="O macOS os oculta sempre que algum ícone está escondido: só aparecem enquanto a barra inteira está visível.",
        ja="macOSはアイコンが1つでも隠れているとこれらを非表示にします。バー全体が表示されている間のみ表示されます。",
        zh="只要有任何图标被隐藏，macOS 就会隐藏这些项目，它们仅在整个菜单栏显示时才会出现。",
        ko="아이콘이 하나라도 숨겨져 있으면 macOS가 이 항목들을 숨깁니다. 막대 전체가 표시될 때만 나타납니다.",
        ru="macOS скрывает их, как только скрыт хотя бы один значок: они видны только при полностью показанной строке меню."),
    "Always hidden": dict(de="Immer ausgeblendet", fr="Toujours masqués", es="Siempre ocultos", it="Sempre nascosti", pt="Sempre ocultos", ja="常に非表示", zh="始终隐藏", ko="항상 숨김", ru="Всегда скрыты"),
    "Show while revealed": dict(de="Beim Einblenden anzeigen", fr="Afficher lorsque la barre est déployée", es="Mostrar mientras esté visible", it="Mostra quando la barra è visibile", pt="Mostrar enquanto revelado", ja="表示中は見せる", zh="显示时可见", ko="표시 중일 때 보이기", ru="Показывать при развёрнутой строке"),
    "Pelmet stays a click away": dict(de="Pelmet bleibt einen Klick entfernt", fr="Pelmet reste à portée de clic", es="Pelmet sigue a un clic", it="Pelmet resta a un clic di distanza", pt="O Pelmet continua a um clique", ja="Pelmetはいつでもすぐに開けます", zh="Pelmet 始终触手可及", ko="Pelmet은 언제나 한 번의 클릭으로 열 수 있습니다", ru="Pelmet всегда в одном клике"),
    "You can always open Pelmet Settings by:\n\n•  Pressing %@\n•  Opening Pelmet again from Spotlight or Finder\n•  Right-clicking any Pelmet separator in the menu bar\n•  Right-clicking an empty spot in the menu bar": dict(
        de="Die Pelmet-Einstellungen sind jederzeit erreichbar:\n\n•  %@ drücken\n•  Pelmet erneut über Spotlight oder den Finder öffnen\n•  Rechtsklick auf einen Pelmet-Trenner in der Menüleiste\n•  Rechtsklick auf eine freie Stelle der Menüleiste",
        fr="Vous pouvez toujours ouvrir les réglages de Pelmet :\n\n•  En appuyant sur %@\n•  En rouvrant Pelmet depuis Spotlight ou le Finder\n•  Par un clic droit sur un séparateur Pelmet dans la barre des menus\n•  Par un clic droit sur une zone vide de la barre des menus",
        es="Siempre puedes abrir los ajustes de Pelmet:\n\n•  Pulsando %@\n•  Abriendo Pelmet de nuevo desde Spotlight o el Finder\n•  Haciendo clic derecho en cualquier separador de Pelmet en la barra de menús\n•  Haciendo clic derecho en un espacio vacío de la barra de menús",
        it="Puoi sempre aprire le impostazioni di Pelmet:\n\n•  Premendo %@\n•  Riaprendo Pelmet da Spotlight o dal Finder\n•  Con un clic destro su un separatore Pelmet nella barra dei menu\n•  Con un clic destro su uno spazio vuoto della barra dei menu",
        pt="Você sempre pode abrir os ajustes do Pelmet:\n\n•  Pressionando %@\n•  Abrindo o Pelmet novamente pelo Spotlight ou pelo Finder\n•  Clicando com o botão direito em qualquer separador do Pelmet na barra de menus\n•  Clicando com o botão direito em um espaço vazio da barra de menus",
        ja="Pelmet設定は次の方法でいつでも開けます：\n\n•  %@ を押す\n•  SpotlightまたはFinderからPelmetを再度開く\n•  メニューバーのPelmet区切りを右クリック\n•  メニューバーの空いている場所を右クリック",
        zh="你随时可以通过以下方式打开 Pelmet 设置：\n\n•  按 %@\n•  在 Spotlight 或访达中再次打开 Pelmet\n•  右键点击菜单栏中的任意 Pelmet 分隔符\n•  右键点击菜单栏的空白处",
        ko="Pelmet 설정은 언제든지 다음 방법으로 열 수 있습니다:\n\n•  %@ 누르기\n•  Spotlight 또는 Finder에서 Pelmet을 다시 열기\n•  메뉴 막대의 Pelmet 구분선을 오른쪽 클릭\n•  메뉴 막대의 빈 곳을 오른쪽 클릭",
        ru="Настройки Pelmet всегда можно открыть:\n\n•  Нажав %@\n•  Снова открыв Pelmet через Spotlight или Finder\n•  Правым щелчком по любому разделителю Pelmet в строке меню\n•  Правым щелчком по пустому месту строки меню"),

    # ── Displays pane ───────────────────────────────────────────────
    "Notch": dict(de="Notch", fr="Encoche", es="Notch", it="Notch", pt="Notch", ja="ノッチ", zh="刘海", ko="노치", ru="Вырез"),
    "Collapse": dict(de="Einklappen", fr="Replier", es="Contraer", it="Comprimi", pt="Recolher", ja="折りたたむ", zh="折叠", ko="접기", ru="Сворачивать"),
    "Expanded": dict(de="Ausgeklappt", fr="Déployée", es="Expandida", it="Espansa", pt="Expandida", ja="展開", zh="展开", ko="펼침", ru="Развёрнуто"),

    # ── About pane ──────────────────────────────────────────────────
    "Version %@ (%@)": dict(de="Version %@ (%@)", fr="Version %@ (%@)", es="Versión %@ (%@)", it="Versione %@ (%@)", pt="Versão %@ (%@)", ja="バージョン %@ (%@)", zh="版本 %@ (%@)", ko="버전 %@ (%@)", ru="Версия %@ (%@)"),
    "Replay the intro": dict(de="Einführung erneut ansehen", fr="Revoir l’introduction", es="Repetir la introducción", it="Rivedi l’introduzione", pt="Rever a introdução", ja="イントロをもう一度見る", zh="重看介绍", ko="소개 다시 보기", ru="Показать вступление снова"),
    "Update to %@": dict(de="Auf %@ aktualisieren", fr="Mettre à jour vers %@", es="Actualizar a %@", it="Aggiorna a %@", pt="Atualizar para %@", ja="%@ にアップデート", zh="更新到 %@", ko="%@(으)로 업데이트", ru="Обновить до %@"),
    "Checking for updates…": dict(de="Suche nach Updates …", fr="Recherche de mises à jour…", es="Buscando actualizaciones…", it="Ricerca aggiornamenti…", pt="Buscando atualizações…", ja="アップデートを確認中…", zh="正在检查更新…", ko="업데이트 확인 중…", ru="Проверка обновлений…"),
    "You're on the latest version": dict(de="Du hast die neueste Version", fr="Vous avez la dernière version", es="Tienes la última versión", it="Hai l’ultima versione", pt="Você está na versão mais recente", ja="最新バージョンです", zh="已是最新版本", ko="최신 버전입니다", ru="У вас последняя версия"),
    "Check for updates": dict(de="Nach Updates suchen", fr="Rechercher des mises à jour", es="Buscar actualizaciones", it="Cerca aggiornamenti", pt="Buscar atualizações", ja="アップデートを確認", zh="检查更新", ko="업데이트 확인", ru="Проверить обновления"),

    # ── Menu Bar tab (editor) ───────────────────────────────────────
    "Hiding is unavailable on this macOS build — reordering still works.": dict(de="Ausblenden ist auf diesem macOS-Build nicht verfügbar – Umsortieren funktioniert weiterhin.", fr="Le masquage n’est pas disponible sur cette version de macOS : le réordonnancement fonctionne toujours.", es="Ocultar no está disponible en esta versión de macOS: reordenar sigue funcionando.", it="Nascondere non è disponibile in questa build di macOS: riordinare funziona ancora.", pt="Ocultar não está disponível nesta versão do macOS: reordenar continua funcionando.", ja="このmacOSビルドでは非表示は使えません。並べ替えは引き続き可能です。", zh="此 macOS 版本不支持隐藏，但仍可重新排序。", ko="이 macOS 빌드에서는 숨기기를 사용할 수 없습니다. 순서 변경은 계속 가능합니다.", ru="Скрытие недоступно в этой сборке macOS: переупорядочивание по-прежнему работает."),
    "Tidying…": dict(de="Wird aufgeräumt …", fr="Rangement…", es="Ordenando…", it="Riordino…", pt="Organizando…", ja="整理中…", zh="正在整理…", ko="정리 중…", ru="Упорядочивание…"),
    "Tidy bar order": dict(de="Leiste aufräumen", fr="Ranger la barre", es="Ordenar la barra", it="Riordina la barra", pt="Organizar a barra", ja="バーの並びを整理", zh="整理菜单栏顺序", ko="막대 순서 정리", ru="Упорядочить строку"),
    "Physically arranges the bar to match the sections — icons that sit out of place slide their neighbors on every reveal.": dict(de="Ordnet die Leiste physisch nach den Bereichen – falsch platzierte Symbole verschieben bei jedem Einblenden ihre Nachbarn.", fr="Réorganise physiquement la barre selon les sections : les icônes mal placées décalent leurs voisines à chaque affichage.", es="Reordena físicamente la barra según las secciones: los iconos fuera de sitio desplazan a sus vecinos en cada aparición.", it="Riordina fisicamente la barra secondo le sezioni: le icone fuori posto spostano le vicine a ogni comparsa.", pt="Reorganiza fisicamente a barra conforme as seções: ícones fora do lugar deslocam os vizinhos a cada revelação.", ja="セクションに合わせてバーを実際に並べ替えます。位置がずれたアイコンは表示のたびに隣のアイコンを動かします。", zh="按分区实际重排菜单栏，位置不当的图标每次显示时都会推挤相邻图标。", ko="섹션에 맞게 막대를 실제로 재배치합니다. 위치가 어긋난 아이콘은 표시될 때마다 이웃을 밀어냅니다.", ru="Физически выстраивает строку по секциям: значки не на своём месте сдвигают соседей при каждом показе."),
    "Input Source": dict(de="Eingabequelle", fr="Source de saisie", es="Fuente de entrada", it="Sorgente di input", pt="Fonte de entrada", ja="入力ソース", zh="输入源", ko="입력 소스", ru="Источник ввода"),
    "Visible": dict(de="Sichtbar", fr="Visibles", es="Visibles", it="Visibili", pt="Visíveis", ja="表示", zh="可见", ko="표시", ru="Видимые"),
    "Always in the menu bar": dict(de="Immer in der Menüleiste", fr="Toujours dans la barre des menus", es="Siempre en la barra de menús", it="Sempre nella barra dei menu", pt="Sempre na barra de menus", ja="常にメニューバーに表示", zh="始终显示在菜单栏", ko="항상 메뉴 막대에 표시", ru="Всегда в строке меню"),
    "Hidden": dict(de="Ausgeblendet", fr="Masqués", es="Ocultos", it="Nascosti", pt="Ocultos", ja="非表示", zh="隐藏", ko="숨김", ru="Скрытые"),
    "A hover or click away — or ⌘-drag icons left of the chevron": dict(de="Ein Überfahren oder Klick entfernt – oder Symbole mit ⌘ links neben den Chevron ziehen", fr="À un survol ou un clic : ou glissez des icônes à gauche du chevron avec ⌘", es="A un paso del cursor o un clic; o arrastra iconos con ⌘ a la izquierda del chevrón", it="A un passaggio del cursore o a un clic; oppure trascina le icone con ⌘ a sinistra del chevron", pt="A um passar de cursor ou clique; ou arraste ícones com ⌘ para a esquerda do chevron", ja="ホバーかクリックで表示。または⌘を押しながらアイコンをシェブロンの左へドラッグ", zh="悬停或点击即可显示，也可按住 ⌘ 将图标拖到尖角符号左侧", ko="마우스를 올리거나 클릭하면 표시. 또는 ⌘를 누른 채 아이콘을 쉐브론 왼쪽으로 드래그", ru="Показ по наведению или щелчку; либо перетащите значки левее шеврона с ⌘"),
    "Always Hidden": dict(de="Immer ausgeblendet", fr="Toujours masqués", es="Siempre ocultos", it="Sempre nascosti", pt="Sempre ocultos", ja="常に非表示", zh="始终隐藏", ko="항상 숨김", ru="Всегда скрытые"),
    "Floating bar": dict(de="Schwebende Leiste", fr="Barre flottante", es="Barra flotante", it="Barra fluttuante", pt="Barra flutuante", ja="フローティングバー", zh="浮动栏", ko="플로팅 바", ru="Плавающая панель"),
    "Show this section in a bar under the menu bar instead of in it": dict(de="Diesen Bereich in einer Leiste unter der Menüleiste zeigen statt in ihr", fr="Afficher cette section dans une barre sous la barre des menus plutôt que dedans", es="Mostrar esta sección en una barra bajo la barra de menús en lugar de en ella", it="Mostra questa sezione in una barra sotto la barra dei menu invece che al suo interno", pt="Mostrar esta seção em uma barra abaixo da barra de menus em vez de nela", ja="このセクションをメニューバー内ではなく、その下のバーに表示", zh="将此分区显示在菜单栏下方的浮动栏中，而不是菜单栏内", ko="이 섹션을 메뉴 막대 안이 아니라 그 아래의 바에 표시", ru="Показывать эту секцию в панели под строкой меню, а не в ней"),
    "Out of sight until you double-click or ⌥-click the chevron": dict(de="Verborgen, bis du den Chevron doppelt oder mit ⌥ anklickst", fr="Hors de vue jusqu’à un double-clic ou un ⌥-clic sur le chevron", es="Fuera de la vista hasta que hagas doble clic o ⌥-clic en el chevrón", it="Fuori vista finché non fai doppio clic o ⌥-clic sul chevron", pt="Fora de vista até você dar clique duplo ou ⌥-clique no chevron", ja="シェブロンをダブルクリックまたは⌥クリックするまで非表示", zh="双击或按住 ⌥ 点击尖角符号之前一直隐藏", ko="쉐브론을 더블 클릭하거나 ⌥-클릭할 때까지 숨김", ru="Скрыты до двойного щелчка или ⌥-щелчка по шеврону"),
    "New menu bar icons go to": dict(de="Neue Menüleistensymbole landen in", fr="Les nouvelles icônes vont dans", es="Los iconos nuevos van a", it="Le nuove icone vanno in", pt="Ícones novos vão para", ja="新しいメニューバーアイコンの行き先", zh="新的菜单栏图标放入", ko="새 메뉴 막대 아이콘 위치", ru="Новые значки попадают в"),
    "Drop icons here": dict(de="Symbole hier ablegen", fr="Déposez des icônes ici", es="Suelta iconos aquí", it="Trascina qui le icone", pt="Solte ícones aqui", ja="ここにアイコンをドロップ", zh="将图标拖放到这里", ko="여기에 아이콘을 놓으세요", ru="Перетащите значки сюда"),
    "New": dict(de="Neu", fr="Nouveau", es="Nuevo", it="Nuovo", pt="Novo", ja="新規", zh="新", ko="새 항목", ru="Новые"),
    "New menu bar icons land here — drag into another section to change it": dict(de="Neue Menüleistensymbole landen hier – in einen anderen Bereich ziehen, um das zu ändern", fr="Les nouvelles icônes arrivent ici : glissez dans une autre section pour changer", es="Los iconos nuevos aparecen aquí; arrastra a otra sección para cambiarlo", it="Le nuove icone arrivano qui: trascina in un’altra sezione per cambiare", pt="Ícones novos chegam aqui; arraste para outra seção para mudar", ja="新しいアイコンはここに入ります。変更するには別のセクションへドラッグ", zh="新图标会放在这里，拖到其他分区可更改", ko="새 아이콘은 여기에 들어옵니다. 바꾸려면 다른 섹션으로 드래그하세요", ru="Новые значки попадают сюда: перетащите в другую секцию, чтобы изменить"),
    "Media": dict(de="Medien", fr="Médias", es="Multimedia", it="Media", pt="Mídia", ja="メディア", zh="媒体", ko="미디어", ru="Медиа"),
    "Camera": dict(de="Kamera", fr="Caméra", es="Cámara", it="Fotocamera", pt="Câmera", ja="カメラ", zh="相机", ko="카메라", ru="Камера"),
    "Separator": dict(de="Trenner", fr="Séparateur", es="Separador", it="Separatore", pt="Separador", ja="区切り", zh="分隔符", ko="구분선", ru="Разделитель"),
    "System": dict(de="System", fr="Système", es="Sistema", it="Sistema", pt="Sistema", ja="システム", zh="系统", ko="시스템", ru="Система"),
    "Icons from the same app hide together": dict(de="Symbole derselben App werden gemeinsam ausgeblendet", fr="Les icônes d’une même app se masquent ensemble", es="Los iconos de la misma app se ocultan juntos", it="Le icone della stessa app si nascondono insieme", pt="Ícones do mesmo app são ocultados juntos", ja="同じアプリのアイコンは一緒に隠れます", zh="同一应用的图标会一起隐藏", ko="같은 앱의 아이콘은 함께 숨겨집니다", ru="Значки одного приложения скрываются вместе"),
    "System icon — Pelmet places it; whether it exists in the bar is set in System Settings › Control Center": dict(de="Systemsymbol – Pelmet platziert es; ob es in der Leiste erscheint, wird in Systemeinstellungen › Kontrollzentrum festgelegt", fr="Icône système : Pelmet la place ; sa présence dans la barre se règle dans Réglages Système › Centre de contrôle", es="Icono del sistema: Pelmet lo coloca; si aparece en la barra se decide en Ajustes del Sistema › Centro de control", it="Icona di sistema: Pelmet la posiziona; la sua presenza nella barra si imposta in Impostazioni di Sistema › Centro di Controllo", pt="Ícone do sistema: o Pelmet o posiciona; se aparece na barra é definido em Ajustes do Sistema › Central de Controle", ja="システムアイコン。Pelmetが配置します。バーに表示するかは「システム設定」›「コントロールセンター」で設定", zh="系统图标，由 Pelmet 摆放；是否显示在菜单栏取决于“系统设置”›“控制中心”", ko="시스템 아이콘. Pelmet이 배치합니다. 막대에 표시할지는 시스템 설정 › 제어 센터에서 정합니다", ru="Системный значок: Pelmet его размещает; показывать ли его в строке, задаётся в Системных настройках › Пункт управления"),
    "Pelmet items": dict(de="Pelmet-Elemente", fr="Éléments Pelmet", es="Elementos de Pelmet", it="Elementi Pelmet", pt="Itens do Pelmet", ja="Pelmetの項目", zh="Pelmet 项目", ko="Pelmet 항목", ru="Элементы Pelmet"),
    "No shortcuts in your library": dict(de="Keine Kurzbefehle in deiner Mediathek", fr="Aucun raccourci dans votre bibliothèque", es="No hay atajos en tu biblioteca", it="Nessun comando rapido nella tua libreria", pt="Nenhum atalho na sua biblioteca", ja="ライブラリにショートカットがありません", zh="资料库中没有快捷指令", ko="보관함에 단축어가 없습니다", ru="В библиотеке нет быстрых команд"),
    "Shortcut": dict(de="Kurzbefehl", fr="Raccourci", es="Atajo", it="Comando rapido", pt="Atalho", ja="ショートカット", zh="快捷指令", ko="단축어", ru="Быстрая команда"),
    "Media controls": dict(de="Mediensteuerung", fr="Commandes multimédias", es="Controles multimedia", it="Controlli multimediali", pt="Controles de mídia", ja="メディアコントロール", zh="媒体控制", ko="미디어 제어", ru="Управление воспроизведением"),
    "Camera & mic indicator": dict(de="Kamera- & Mikrofonanzeige", fr="Indicateur caméra et micro", es="Indicador de cámara y micro", it="Indicatore fotocamera e microfono", pt="Indicador de câmera e microfone", ja="カメラ＆マイクのインジケータ", zh="相机和麦克风指示器", ko="카메라 및 마이크 표시기", ru="Индикатор камеры и микрофона"),
    "Static": dict(de="Statisch", fr="Statique", es="Estático", it="Statico", pt="Estático", ja="静止", zh="静态", ko="정적", ru="Статичный"),
    "Animated": dict(de="Animiert", fr="Animé", es="Animado", it="Animato", pt="Animado", ja="アニメーション", zh="动态", ko="애니메이션", ru="Анимированный"),
    "AirDrop": dict(de="AirDrop", fr="AirDrop", es="AirDrop", it="AirDrop", pt="AirDrop", ja="AirDrop", zh="隔空投送", ko="AirDrop", ru="AirDrop"),
    "Separators": dict(de="Trenner", fr="Séparateurs", es="Separadores", it="Separatori", pt="Separadores", ja="区切り", zh="分隔符", ko="구분선", ru="Разделители"),
    "Separator opacity in the menu bar": dict(de="Deckkraft des Trenners in der Menüleiste", fr="Opacité du séparateur dans la barre des menus", es="Opacidad del separador en la barra de menús", it="Opacità del separatore nella barra dei menu", pt="Opacidade do separador na barra de menus", ja="メニューバーでの区切りの不透明度", zh="分隔符在菜单栏中的不透明度", ko="메뉴 막대에서 구분선의 불투명도", ru="Непрозрачность разделителя в строке меню"),
    "Pipe": dict(de="Strich", fr="Barre verticale", es="Barra vertical", it="Barra verticale", pt="Barra vertical", ja="縦線", zh="竖线", ko="세로선", ru="Вертикальная черта"),
    "Dot": dict(de="Punkt", fr="Point", es="Punto", it="Punto", pt="Ponto", ja="ドット", zh="圆点", ko="점", ru="Точка"),
    "Chevron ‹": dict(de="Chevron ‹", fr="Chevron ‹", es="Chevrón ‹", it="Chevron ‹", pt="Chevron ‹", ja="シェブロン ‹", zh="尖角符号 ‹", ko="쉐브론 ‹", ru="Шеврон ‹"),
    "Chevron ›": dict(de="Chevron ›", fr="Chevron ›", es="Chevrón ›", it="Chevron ›", pt="Chevron ›", ja="シェブロン ›", zh="尖角符号 ›", ko="쉐브론 ›", ru="Шеврон ›"),
    "Dash": dict(de="Gedankenstrich", fr="Tiret", es="Guion", it="Trattino", pt="Travessão", ja="ダッシュ", zh="破折号", ko="대시", ru="Тире"),
    "Invisible spacer": dict(de="Unsichtbarer Abstand", fr="Espace invisible", es="Espaciador invisible", it="Spaziatore invisibile", pt="Espaçador invisível", ja="見えないスペース", zh="不可见间隔", ko="보이지 않는 간격", ru="Невидимый отступ"),

    # ── Onboarding ──────────────────────────────────────────────────
    "Back": dict(de="Zurück", fr="Retour", es="Atrás", it="Indietro", pt="Voltar", ja="戻る", zh="返回", ko="뒤로", ru="Назад"),
    "Continue": dict(de="Weiter", fr="Continuer", es="Continuar", it="Continua", pt="Continuar", ja="続ける", zh="继续", ko="계속", ru="Далее"),
    "Start using Pelmet": dict(de="Pelmet verwenden", fr="Commencer avec Pelmet", es="Empezar a usar Pelmet", it="Inizia a usare Pelmet", pt="Começar a usar o Pelmet", ja="Pelmetを使い始める", zh="开始使用 Pelmet", ko="Pelmet 사용 시작", ru="Начать работу с Pelmet"),
    "Your menu bar,\ntucked away.": dict(de="Deine Menüleiste,\naufgeräumt.", fr="Votre barre des menus,\nbien rangée.", es="Tu barra de menús,\nrecogida.", it="La tua barra dei menu,\nin ordine.", pt="Sua barra de menus,\nbem guardada.", ja="メニューバーを、\nすっきりと。", zh="你的菜单栏，\n收纳整齐。", ko="메뉴 막대를\n깔끔하게 정리.", ru="Строка меню,\nубранная с глаз."),
    "Pelmet keeps every icon a hover away — and the ones you never need, out of sight.": dict(de="Pelmet hält jedes Symbol ein Überfahren entfernt – und die, die du nie brauchst, außer Sicht.", fr="Pelmet garde chaque icône à un survol, et celles dont vous n’avez jamais besoin, hors de vue.", es="Pelmet mantiene cada icono a un paso del cursor, y los que nunca necesitas, fuera de la vista.", it="Pelmet tiene ogni icona a un passaggio del cursore, e quelle che non ti servono mai, fuori vista.", pt="O Pelmet mantém cada ícone a um passar de cursor, e os que você nunca precisa, fora de vista.", ja="Pelmetはすべてのアイコンをホバー一つで呼び出せるようにし、不要なものは視界から隠します。", zh="Pelmet 让每个图标悬停即现，而那些你从不需要的，则藏于视线之外。", ko="Pelmet은 모든 아이콘을 마우스 한 번에 불러오고, 필요 없는 것은 시야 밖으로 치웁니다.", ru="Pelmet держит каждый значок в одном наведении, а те, что не нужны никогда, — вне поля зрения."),
    "Access granted": dict(de="Zugriff gewährt", fr="Accès accordé", es="Acceso concedido", it="Accesso concesso", pt="Acesso concedido", ja="アクセスが許可されました", zh="已授权", ko="접근 허용됨", ru="Доступ предоставлен"),
    "Grant Accessibility Access": dict(de="Bedienungshilfen-Zugriff erlauben", fr="Autoriser l’accessibilité", es="Conceder acceso de accesibilidad", it="Consenti l’accessibilità", pt="Conceder acesso de acessibilidade", ja="アクセシビリティを許可", zh="授予辅助功能权限", ko="손쉬운 사용 접근 허용", ru="Разрешить Универсальный доступ"),
    "Drag the icon left\nof the chevron.": dict(de="Zieh das Symbol links\nneben den Chevron.", fr="Glissez l’icône\nà gauche du chevron.", es="Arrastra el icono\na la izquierda del chevrón.", it="Trascina l’icona\na sinistra del chevron.", pt="Arraste o ícone\npara a esquerda do chevron.", ja="アイコンをシェブロンの\n左へドラッグ。", zh="把图标拖到\n尖角符号左侧。", ko="아이콘을 쉐브론\n왼쪽으로 드래그.", ru="Перетащите значок\nлевее шеврона."),
    "That's the whole trick.": dict(de="Das ist der ganze Trick.", fr="C’est tout le secret.", es="Ese es todo el truco.", it="Tutto qui.", pt="É só isso.", ja="コツはそれだけ。", zh="就这么简单。", ko="비결은 이게 전부입니다.", ru="Вот и весь секрет."),
    "The chevron is the boundary: everything left of it tucks away.": dict(de="Der Chevron ist die Grenze: Alles links davon wird verstaut.", fr="Le chevron est la frontière : tout ce qui est à sa gauche se range.", es="El chevrón es la frontera: todo lo que queda a su izquierda se recoge.", it="Il chevron è il confine: tutto ciò che sta a sinistra si ripiega.", pt="O chevron é a fronteira: tudo à esquerda dele se recolhe.", ja="シェブロンが境界です。その左にあるものはすべて隠れます。", zh="尖角符号就是分界线：它左侧的一切都会收起。", ko="쉐브론이 경계입니다. 왼쪽의 모든 것이 숨겨집니다.", ru="Шеврон — это граница: всё левее него прячется."),
    "Left of the chevron hides, right stays. In your real bar, hold ⌘ while dragging — or arrange everything in Pelmet's settings.": dict(
        de="Links vom Chevron wird ausgeblendet, rechts bleibt sichtbar. In deiner echten Leiste hältst du beim Ziehen ⌘ gedrückt – oder ordnest alles in den Pelmet-Einstellungen.",
        fr="À gauche du chevron, masqué ; à droite, visible. Dans votre vraie barre, maintenez ⌘ en glissant, ou organisez tout dans les réglages de Pelmet.",
        es="A la izquierda del chevrón se oculta, a la derecha se queda. En tu barra real, mantén ⌘ mientras arrastras, o colócalo todo desde los ajustes de Pelmet.",
        it="A sinistra del chevron si nasconde, a destra resta. Nella barra vera tieni premuto ⌘ mentre trascini, oppure sistema tutto nelle impostazioni di Pelmet.",
        pt="À esquerda do chevron fica oculto, à direita fica visível. Na sua barra real, segure ⌘ ao arrastar, ou organize tudo nos ajustes do Pelmet.",
        ja="シェブロンの左は隠れ、右は残ります。実際のバーでは⌘を押しながらドラッグするか、Pelmetの設定ですべてを並べ替えられます。",
        zh="尖角符号左侧隐藏，右侧保留。在真实菜单栏中，拖动时按住 ⌘，或在 Pelmet 设置中统一安排。",
        ko="쉐브론 왼쪽은 숨고 오른쪽은 남습니다. 실제 막대에서는 ⌘를 누른 채 드래그하거나, Pelmet 설정에서 모두 정리하세요.",
        ru="Левее шеврона — скрыто, правее — видно. В настоящей строке удерживайте ⌘ при перетаскивании или расставьте всё в настройках Pelmet."),
    "Settled in.": dict(de="Eingerichtet.", fr="Bien installé.", es="Todo listo.", it="Tutto a posto.", pt="Tudo pronto.", ja="準備完了。", zh="一切就绪。", ko="준비 완료.", ru="Всё готово."),
    "Hover the bar to peek, click the chevron to toggle (⌥⌘, does it from anywhere), right-click it for settings. Everything else is arrangeable in Pelmet Settings › Menu Bar.": dict(
        de="Leiste überfahren zum Spicken, Chevron anklicken zum Umschalten (⌥⌘, geht von überall), Rechtsklick für die Einstellungen. Alles Weitere ordnest du unter Pelmet-Einstellungen › Menüleiste.",
        fr="Survolez la barre pour jeter un œil, cliquez sur le chevron pour basculer (⌥⌘, le fait de n’importe où), clic droit pour les réglages. Tout le reste s’organise dans Réglages de Pelmet › Barre des menus.",
        es="Pasa el cursor por la barra para echar un vistazo, haz clic en el chevrón para alternar (⌥⌘, lo hace desde cualquier app) y clic derecho para los ajustes. Todo lo demás se organiza en Ajustes de Pelmet › Barra de menús.",
        it="Passa il cursore sulla barra per sbirciare, fai clic sul chevron per alternare (⌥⌘, lo fa da qualsiasi app), clic destro per le impostazioni. Tutto il resto si sistema in Impostazioni di Pelmet › Barra dei menu.",
        pt="Passe o cursor na barra para espiar, clique no chevron para alternar (⌥⌘, faz isso de qualquer app), clique com o botão direito para os ajustes. Todo o resto se organiza em Ajustes do Pelmet › Barra de menus.",
        ja="バーにホバーでちらっと表示、シェブロンをクリックで切り替え（⌥⌘, ならどこからでも）、右クリックで設定。その他はすべて「Pelmet設定」›「メニューバー」で並べ替えられます。",
        zh="悬停菜单栏可快速查看，点击尖角符号切换（⌥⌘, 在任何地方都可以），右键打开设置。其余一切可在 Pelmet 设置 › 菜单栏中安排。",
        ko="막대에 마우스를 올려 살짝 보고, 쉐브론을 클릭해 전환하고(⌥⌘, 로 어디서든 가능), 오른쪽 클릭으로 설정을 엽니다. 나머지는 모두 Pelmet 설정 › 메뉴 막대에서 정리할 수 있습니다.",
        ru="Наведите на строку, чтобы взглянуть, щёлкните шеврон для переключения (⌥⌘, работает отовсюду), правый щелчок — настройки. Всё остальное настраивается в Настройки Pelmet › Строка меню."),
    "Open Pelmet at login": dict(de="Pelmet bei der Anmeldung öffnen", fr="Ouvrir Pelmet à l’ouverture de session", es="Abrir Pelmet al iniciar sesión", it="Apri Pelmet al login", pt="Abrir o Pelmet ao iniciar sessão", ja="ログイン時にPelmetを開く", zh="登录时打开 Pelmet", ko="로그인 시 Pelmet 열기", ru="Открывать Pelmet при входе"),
    "Drag me left of the chevron": dict(de="Zieh mich links neben den Chevron", fr="Glissez-moi à gauche du chevron", es="Arrástrame a la izquierda del chevrón", it="Trascinami a sinistra del chevron", pt="Arraste-me para a esquerda do chevron", ja="シェブロンの左へドラッグしてください", zh="把我拖到尖角符号左侧", ko="쉐브론 왼쪽으로 드래그하세요", ru="Перетащите меня левее шеврона"),

    # ── Status item menu ────────────────────────────────────────────
    "Hide Items": dict(de="Objekte ausblenden", fr="Masquer les éléments", es="Ocultar elementos", it="Nascondi elementi", pt="Ocultar itens", ja="項目を隠す", zh="隐藏项目", ko="항목 숨기기", ru="Скрыть элементы"),
    "Show Hidden Items": dict(de="Ausgeblendete Objekte einblenden", fr="Afficher les éléments masqués", es="Mostrar elementos ocultos", it="Mostra elementi nascosti", pt="Mostrar itens ocultos", ja="隠した項目を表示", zh="显示隐藏的项目", ko="숨긴 항목 표시", ru="Показать скрытые элементы"),
    "Show Always-Hidden Too": dict(de="Auch „Immer ausgeblendet“ einblenden", fr="Afficher aussi les toujours masqués", es="Mostrar también los siempre ocultos", it="Mostra anche i sempre nascosti", pt="Mostrar também os sempre ocultos", ja="「常に非表示」も表示", zh="同时显示“始终隐藏”的项目", ko="항상 숨김 항목도 표시", ru="Показать и всегда скрытые"),
    "Pelmet Settings…": dict(de="Pelmet-Einstellungen …", fr="Réglages de Pelmet…", es="Ajustes de Pelmet…", it="Impostazioni di Pelmet…", pt="Ajustes do Pelmet…", ja="Pelmet設定…", zh="Pelmet 设置…", ko="Pelmet 설정…", ru="Настройки Pelmet…"),
    "Quit Pelmet": dict(de="Pelmet beenden", fr="Quitter Pelmet", es="Salir de Pelmet", it="Esci da Pelmet", pt="Encerrar o Pelmet", ja="Pelmetを終了", zh="退出 Pelmet", ko="Pelmet 종료", ru="Завершить Pelmet"),

    # ── Media / camera extras ───────────────────────────────────────
    "Previous Track": dict(de="Vorheriger Titel", fr="Piste précédente", es="Pista anterior", it="Brano precedente", pt="Faixa anterior", ja="前の曲", zh="上一曲", ko="이전 트랙", ru="Предыдущий трек"),
    "Next Track": dict(de="Nächster Titel", fr="Piste suivante", es="Pista siguiente", it="Brano successivo", pt="Próxima faixa", ja="次の曲", zh="下一曲", ko="다음 트랙", ru="Следующий трек"),
    "Camera & Mic": dict(de="Kamera & Mikrofon", fr="Caméra et micro", es="Cámara y micro", it="Fotocamera e microfono", pt="Câmera e microfone", ja="カメラ＆マイク", zh="相机和麦克风", ko="카메라 및 마이크", ru="Камера и микрофон"),
    # ── Permissions (General) + status item warning ─────────────────
    "Permissions": dict(de="Berechtigungen", fr="Autorisations", es="Permisos", it="Autorizzazioni", pt="Permissões", ja="権限", zh="权限", ko="권한", ru="Разрешения"),
    "Accessibility": dict(de="Bedienungshilfen", fr="Accessibilité", es="Accesibilidad", it="Accessibilità", pt="Acessibilidade", ja="アクセシビリティ", zh="辅助功能", ko="손쉬운 사용", ru="Универсальный доступ"),
    "How Pelmet sees the menu bar and moves its icons.": dict(de="So sieht Pelmet die Menüleiste und bewegt ihre Symbole.", fr="C’est ainsi que Pelmet voit la barre des menus et déplace ses icônes.", es="Así es como Pelmet ve la barra de menús y mueve sus iconos.", it="È così che Pelmet vede la barra dei menu e ne sposta le icone.", pt="É assim que o Pelmet vê a barra de menus e move seus ícones.", ja="Pelmetがメニューバーを認識し、アイコンを動かすための権限です。", zh="Pelmet 借此识别菜单栏并移动其图标。", ko="Pelmet이 메뉴 막대를 인식하고 아이콘을 옮기는 데 사용됩니다.", ru="Так Pelmet видит строку меню и перемещает её значки."),
    "Off. Pelmet can't see or arrange the menu bar without it.": dict(de="Aus. Ohne sie kann Pelmet die Menüleiste weder sehen noch ordnen.", fr="Désactivée. Sans elle, Pelmet ne peut ni voir ni organiser la barre des menus.", es="Desactivada. Sin ella, Pelmet no puede ver ni organizar la barra de menús.", it="Disattivata. Senza, Pelmet non può vedere né organizzare la barra dei menu.", pt="Desativada. Sem ela, o Pelmet não consegue ver nem organizar a barra de menus.", ja="オフです。この権限がないとPelmetはメニューバーを認識も整理もできません。", zh="已关闭。没有它，Pelmet 无法识别或整理菜单栏。", ko="꺼짐. 이 권한이 없으면 Pelmet은 메뉴 막대를 인식하거나 정리할 수 없습니다.", ru="Выключено. Без него Pelmet не видит строку меню и не может её упорядочить."),
    "Granted": dict(de="Erteilt", fr="Accordée", es="Concedido", it="Concessa", pt="Concedida", ja="許可済み", zh="已授权", ko="허용됨", ru="Предоставлено"),
    "Grant access": dict(de="Zugriff erlauben", fr="Accorder l’accès", es="Conceder acceso", it="Concedi l’accesso", pt="Conceder acesso", ja="アクセスを許可", zh="授予访问权限", ko="접근 허용", ru="Разрешить доступ"),
    "Accessibility access is off. Turn it on…": dict(de="Bedienungshilfen-Zugriff ist aus. Einschalten …", fr="L’accès Accessibilité est désactivé. L’activer…", es="El acceso de Accesibilidad está desactivado. Activarlo…", it="L’accesso Accessibilità è disattivato. Attivalo…", pt="O acesso de Acessibilidade está desativado. Ativar…", ja="アクセシビリティのアクセスがオフです。オンにする…", zh="辅助功能访问已关闭。开启…", ko="손쉬운 사용 접근이 꺼져 있습니다. 켜기…", ru="Доступ «Универсальный доступ» выключен. Включить…"),

    # ── Screen Recording (General permissions row + Access step, issue #6) ──
    "Screen Recording": dict(de="Bildschirmaufnahme", fr="Enregistrement de l’écran", es="Grabación de pantalla", it="Registrazione schermo", pt="Gravação de tela", ja="画面収録", zh="屏幕录制", ko="화면 기록", ru="Запись экрана"),
    "Lets the animation styles play over the system's own show and hide.": dict(de="Lässt die Animationsstile über dem Ein- und Ausblenden des Systems laufen.", fr="Permet aux styles d’animation de se jouer par-dessus l’affichage et le masquage du système.", es="Permite que los estilos de animación se reproduzcan sobre el mostrar y ocultar del sistema.", it="Consente agli stili di animazione di sovrapporsi al mostra/nascondi del sistema.", pt="Permite que os estilos de animação rodem sobre o mostrar e esconder do sistema.", ja="アニメーションスタイルをシステム標準の表示・非表示の上で再生できるようにします。", zh="让动画样式覆盖在系统自带的显示与隐藏之上。", ko="애니메이션 스타일이 시스템의 표시/숨김 위에서 재생되게 합니다.", ru="Позволяет стилям анимации проигрываться поверх системного показа и скрытия."),
    "Optional. Without it, icons show and hide the way macOS does it.": dict(de="Optional. Ohne sie erscheinen und verschwinden Symbole so, wie macOS es tut.", fr="Facultatif. Sans lui, les icônes apparaissent et disparaissent comme macOS le fait.", es="Opcional. Sin él, los iconos se muestran y ocultan como lo hace macOS.", it="Facoltativo. Senza, le icone appaiono e scompaiono come fa macOS.", pt="Opcional. Sem ela, os ícones aparecem e somem como o macOS faz.", ja="任意です。なければmacOSと同じようにアイコンが表示・非表示になります。", zh="可选。没有它，图标会按 macOS 的方式显示和隐藏。", ko="선택 사항입니다. 없으면 macOS 방식대로 아이콘이 표시되고 숨겨집니다.", ru="Необязательно. Без него значки показываются и скрываются так, как это делает macOS."),
    "Two permissions.": dict(de="Zwei Berechtigungen.", fr="Deux autorisations.", es="Dos permisos.", it="Due autorizzazioni.", pt="Duas permissões.", ja="2つの権限。", zh="两个权限。", ko="두 가지 권한.", ru="Два разрешения."),
    "Accessibility is how Pelmet sees the icons and moves them, nothing leaves your Mac. Screen Recording is optional: it lets Pelmet's animation styles play over the way macOS shows and hides icons. Nothing is recorded or kept.": dict(
        de="Über die Bedienungshilfen sieht Pelmet die Symbole und bewegt sie, nichts verlässt deinen Mac. Bildschirmaufnahme ist optional: Sie lässt Pelmets Animationsstile über dem Ein- und Ausblenden von macOS laufen. Es wird nichts aufgezeichnet oder gespeichert.",
        fr="L’accessibilité est ce qui permet à Pelmet de voir les icônes et de les déplacer, rien ne quitte votre Mac. L’enregistrement de l’écran est facultatif : il permet aux styles d’animation de Pelmet de se jouer par-dessus la façon dont macOS affiche et masque les icônes. Rien n’est enregistré ni conservé.",
        es="La accesibilidad es cómo Pelmet ve los iconos y los mueve, nada sale de tu Mac. La grabación de pantalla es opcional: permite que los estilos de animación de Pelmet se reproduzcan sobre la forma en que macOS muestra y oculta los iconos. No se graba ni se guarda nada.",
        it="L’accessibilità è il modo in cui Pelmet vede le icone e le sposta, nulla lascia il tuo Mac. La registrazione schermo è facoltativa: consente agli stili di animazione di Pelmet di sovrapporsi al modo in cui macOS mostra e nasconde le icone. Non viene registrato né conservato nulla.",
        pt="A acessibilidade é como o Pelmet vê os ícones e os move, nada sai do seu Mac. A gravação de tela é opcional: permite que os estilos de animação do Pelmet rodem sobre a forma como o macOS mostra e esconde os ícones. Nada é gravado nem guardado.",
        ja="アクセシビリティは、Pelmetがアイコンを認識して移動するための仕組みで、データがMacの外に出ることはありません。画面収録は任意です。Pelmetのアニメーションスタイルを、macOS標準のアイコン表示・非表示の上で再生できるようにします。何も記録・保存されません。",
        zh="辅助功能是 Pelmet 识别并移动图标的方式，数据不会离开你的 Mac。屏幕录制是可选的：它让 Pelmet 的动画样式覆盖在 macOS 显示和隐藏图标的方式之上。不会录制或保存任何内容。",
        ko="손쉬운 사용은 Pelmet이 아이콘을 인식하고 옮기는 방식이며 어떤 것도 Mac 밖으로 나가지 않습니다. 화면 기록은 선택 사항입니다. Pelmet의 애니메이션 스타일이 macOS가 아이콘을 표시하고 숨기는 방식 위에서 재생되게 합니다. 아무것도 기록하거나 저장하지 않습니다.",
        ru="Универсальный доступ — так Pelmet видит значки и перемещает их, ничего не покидает ваш Mac. Запись экрана необязательна: она позволяет стилям анимации Pelmet проигрываться поверх того, как macOS показывает и скрывает значки. Ничего не записывается и не хранится."),
    "Screen Recording on": dict(de="Bildschirmaufnahme aktiv", fr="Enregistrement de l’écran activé", es="Grabación de pantalla activada", it="Registrazione schermo attiva", pt="Gravação de tela ativada", ja="画面収録オン", zh="屏幕录制已开启", ko="화면 기록 켜짐", ru="Запись экрана включена"),
    "Allow Screen Recording": dict(de="Bildschirmaufnahme erlauben", fr="Autoriser l’enregistrement de l’écran", es="Permitir grabación de pantalla", it="Consenti registrazione schermo", pt="Permitir gravação de tela", ja="画面収録を許可", zh="允许屏幕录制", ko="화면 기록 허용", ru="Разрешить запись экрана"),
    "Optional": dict(de="Optional", fr="Facultatif", es="Opcional", it="Facoltativo", pt="Opcional", ja="任意", zh="可选", ko="선택 사항", ru="Необязательно"),

    # ── Animation card (Behavior) ───────────────────────────────────
    "Animation": dict(de="Animation", fr="Animation", es="Animación", it="Animazione", pt="Animação", ja="アニメーション", zh="动画", ko="애니메이션", ru="Анимация"),

    "Active": dict(de="Aktiv", fr="Actif", es="Activo", it="Attivo", pt="Ativo", ja="使用中", zh="当前", ko="사용 중", ru="Активно"),

    # ── Access recovery (onboarding window, one beat) ───────────────
    "Access got lost.": dict(de="Zugriff verloren.", fr="L’accès s’est perdu.", es="Se perdió el acceso.", it="L’accesso è andato perso.", pt="O acesso se perdeu.", ja="アクセスが失われました。", zh="访问权限丢失了。", ko="접근 권한이 사라졌습니다.", ru="Доступ потерян."),
    "macOS dropped Pelmet's accessibility permission, which happens after some updates and reinstalls. Grant it again and everything picks up where it left off.": dict(
        de="macOS hat Pelmets Bedienungshilfen-Berechtigung verworfen, was nach manchen Updates und Neuinstallationen passiert. Erteile sie erneut, und alles macht dort weiter, wo es aufgehört hat.",
        fr="macOS a retiré l’autorisation d’accessibilité de Pelmet, ce qui arrive après certaines mises à jour et réinstallations. Accordez-la à nouveau et tout reprend là où ça s’était arrêté.",
        es="macOS retiró el permiso de accesibilidad de Pelmet, algo que ocurre tras algunas actualizaciones y reinstalaciones. Concédelo de nuevo y todo continúa donde se quedó.",
        it="macOS ha rimosso l’autorizzazione Accessibilità di Pelmet, cosa che succede dopo alcuni aggiornamenti e reinstallazioni. Concedila di nuovo e tutto riprende da dove si era fermato.",
        pt="O macOS retirou a permissão de acessibilidade do Pelmet, o que acontece após algumas atualizações e reinstalações. Conceda-a de novo e tudo continua de onde parou.",
        ja="macOSがPelmetのアクセシビリティ権限を解除しました。一部のアップデートや再インストールの後に起こることがあります。もう一度許可すれば、すべて元どおりに再開します。",
        zh="macOS 移除了 Pelmet 的辅助功能权限，这在某些更新和重新安装后会发生。重新授予后，一切会从上次的状态继续。",
        ko="macOS가 Pelmet의 손쉬운 사용 권한을 해제했습니다. 일부 업데이트나 재설치 후에 일어나는 일입니다. 다시 허용하면 모든 것이 이전 상태에서 이어집니다.",
        ru="macOS сбросила разрешение Pelmet на универсальный доступ — так бывает после некоторых обновлений и переустановок. Предоставьте его снова, и всё продолжится с того же места."),
    "Done": dict(de="Fertig", fr="Terminé", es="Listo", it="Fine", pt="Concluído", ja="完了", zh="完成", ko="완료", ru="Готово"),

    # ── About: links + updates ──────────────────────────────────────
    "Website": dict(de="Website", fr="Site web", es="Sitio web", it="Sito web", pt="Site", ja="Webサイト", zh="网站", ko="웹사이트", ru="Сайт"),
    "GitHub": dict(de="GitHub", fr="GitHub", es="GitHub", it="GitHub", pt="GitHub", ja="GitHub", zh="GitHub", ko="GitHub", ru="GitHub"),
    "Report an issue": dict(de="Problem melden", fr="Signaler un problème", es="Informar de un problema", it="Segnala un problema", pt="Relatar um problema", ja="問題を報告", zh="报告问题", ko="문제 신고", ru="Сообщить о проблеме"),
    "Updates": dict(de="Updates", fr="Mises à jour", es="Actualizaciones", it="Aggiornamenti", pt="Atualizações", ja="アップデート", zh="更新", ko="업데이트", ru="Обновления"),
    "Download updates automatically": dict(de="Updates automatisch laden", fr="Télécharger les mises à jour automatiquement", es="Descargar actualizaciones automáticamente", it="Scarica gli aggiornamenti automaticamente", pt="Baixar atualizações automaticamente", ja="アップデートを自動でダウンロード", zh="自动下载更新", ko="업데이트 자동 다운로드", ru="Загружать обновления автоматически"),
    "Installs on the next quit.": dict(de="Wird beim nächsten Beenden installiert.", fr="S’installe à la prochaine fermeture.", es="Se instala al salir la próxima vez.", it="Si installa alla prossima uscita.", pt="Instala ao encerrar da próxima vez.", ja="次回終了時にインストールされます。", zh="下次退出时安装。", ko="다음에 종료할 때 설치됩니다.", ru="Установится при следующем выходе."),
    "Notify me when an update is available": dict(de="Benachrichtigen, wenn ein Update verfügbar ist", fr="Me prévenir quand une mise à jour est disponible", es="Avisarme cuando haya una actualización", it="Avvisami quando è disponibile un aggiornamento", pt="Avisar quando houver uma atualização", ja="アップデートがあれば通知", zh="有可用更新时通知我", ko="업데이트가 있으면 알림", ru="Уведомлять о новых обновлениях"),
    "Last checked %@": dict(de="Zuletzt geprüft %@", fr="Dernière vérification %@", es="Última comprobación %@", it="Ultimo controllo %@", pt="Última verificação %@", ja="最終確認 %@", zh="上次检查 %@", ko="마지막 확인 %@", ru="Последняя проверка %@"),
    "Update": dict(de="Update", fr="Mise à jour", es="Actualizar", it="Aggiorna", pt="Atualizar", ja="更新", zh="更新", ko="업데이트", ru="Обновить"),
    "Update to %@…": dict(de="Auf %@ aktualisieren …", fr="Mettre à jour vers %@…", es="Actualizar a %@…", it="Aggiorna a %@…", pt="Atualizar para %@…", ja="%@ にアップデート…", zh="更新到 %@…", ko="%@(으)로 업데이트…", ru="Обновить до %@…"),
    "Pelmet %@ is available": dict(de="Pelmet %@ ist verfügbar", fr="Pelmet %@ est disponible", es="Pelmet %@ está disponible", it="Pelmet %@ è disponibile", pt="Pelmet %@ está disponível", ja="Pelmet %@ が利用可能です", zh="Pelmet %@ 已可用", ko="Pelmet %@ 사용 가능", ru="Доступна версия Pelmet %@"),
    "Pelmet %@ is ready": dict(de="Pelmet %@ ist bereit", fr="Pelmet %@ est prêt", es="Pelmet %@ está listo", it="Pelmet %@ è pronto", pt="Pelmet %@ está pronto", ja="Pelmet %@ の準備ができました", zh="Pelmet %@ 已准备就绪", ko="Pelmet %@ 준비 완료", ru="Pelmet %@ готов к установке"),
    "Installs when you quit. Click to update now.": dict(de="Wird beim Beenden installiert. Zum sofortigen Aktualisieren klicken.", fr="S’installe à la fermeture. Cliquez pour mettre à jour maintenant.", es="Se instala al salir. Haz clic para actualizar ahora.", it="Si installa all’uscita. Fai clic per aggiornare adesso.", pt="Instala ao encerrar. Clique para atualizar agora.", ja="終了時にインストールされます。今すぐ更新するにはクリック。", zh="退出时安装。点击立即更新。", ko="종료할 때 설치됩니다. 지금 업데이트하려면 클릭하세요.", ru="Установится при выходе. Нажмите, чтобы обновить сейчас."),
    "A few seconds and a relaunch. Click to update.": dict(de="Ein paar Sekunden und ein Neustart. Zum Aktualisieren klicken.", fr="Quelques secondes et un redémarrage. Cliquez pour mettre à jour.", es="Unos segundos y un reinicio. Haz clic para actualizar.", it="Pochi secondi e un riavvio. Fai clic per aggiornare.", pt="Alguns segundos e um reinício. Clique para atualizar.", ja="数秒と再起動だけ。クリックしてアップデート。", zh="只需几秒钟并重新启动。点击以更新。", ko="몇 초와 다시 실행이면 됩니다. 클릭하여 업데이트하세요.", ru="Пара секунд и перезапуск. Нажмите, чтобы обновить."),

    # ── App stand-ins ───────────────────────────────────────────────
    "App": dict(de="App", fr="App", es="App", it="App", pt="App", ja="アプリ", zh="应用", ko="앱", ru="Приложение"),
    "Choose an app…": dict(de="App auswählen …", fr="Choisir une app…", es="Elegir una app…", it="Scegli un’app…", pt="Escolher um app…", ja="アプリを選択…", zh="选择应用…", ko="앱 선택…", ru="Выбрать приложение…"),
    "Learn more": dict(de="Mehr erfahren", fr="En savoir plus", es="Más información", it="Scopri di più", pt="Saiba mais", ja="詳しく見る", zh="了解更多", ko="더 알아보기", ru="Подробнее"),
    "Why can't Pelmet hide this?": dict(de="Warum kann Pelmet das nicht ausblenden?", fr="Pourquoi Pelmet ne peut-il pas masquer ceci ?", es="¿Por qué Pelmet no puede ocultar esto?", it="Perché Pelmet non può nasconderla?", pt="Por que o Pelmet não consegue ocultar isto?", ja="なぜPelmetはこれを隠せないの？", zh="为什么 Pelmet 无法隐藏它？", ko="Pelmet이 왜 이것을 숨길 수 없나요?", ru="Почему Pelmet не может это скрыть?"),
    "macOS kept it in the bar when Pelmet asked to hide it.": dict(de="macOS hat es in der Leiste behalten, als Pelmet es ausblenden wollte.", fr="macOS l’a gardée dans la barre quand Pelmet a demandé à la masquer.", es="macOS lo mantuvo en la barra cuando Pelmet pidió ocultarlo.", it="macOS l’ha tenuta nella barra quando Pelmet ha chiesto di nasconderla.", pt="O macOS o manteve na barra quando o Pelmet pediu para ocultá-lo.", ja="Pelmetが隠すよう求めても、macOSがバーに残しました。", zh="Pelmet 请求隐藏时，macOS 仍将它保留在菜单栏中。", ko="Pelmet이 숨기려 했을 때 macOS가 막대에 그대로 두었습니다.", ru="macOS оставила его в строке, когда Pelmet попросил его скрыть."),
    "Then turn the original off in %@'s settings.": dict(de="Schalte danach das Original in den Einstellungen von %@ aus.", fr="Ensuite, désactivez l’originale dans les réglages de %@.", es="Después, desactiva el original en los ajustes de %@.", it="Poi disattiva l’originale nelle impostazioni di %@.", pt="Depois, desative o original nos ajustes de %@.", ja="そのあと、%@ の設定で元のアイコンをオフにしてください。", zh="然后在 %@ 的设置中关闭原图标。", ko="그런 다음 %@ 설정에서 원래 아이콘을 끄세요.", ru="Затем отключите оригинал в настройках %@."),
    "Pinned by macOS": dict(de="Von macOS fixiert", fr="Épinglé par macOS", es="Fijado por macOS", it="Fissato da macOS", pt="Fixado pelo macOS", ja="macOSにより固定", zh="由 macOS 固定", ko="macOS가 고정함", ru="Закреплено macOS"),
    "Pelmet can hide %@, but macOS keeps it in its own spot, so the editor can't move it.": dict(
        de="Pelmet kann %@ ausblenden, aber macOS hält es an seinem Platz, der Editor kann es also nicht verschieben.",
        fr="Pelmet peut masquer %@, mais macOS le garde à sa place, l'éditeur ne peut donc pas le déplacer.",
        es="Pelmet puede ocultar %@, pero macOS lo mantiene en su sitio, así que el editor no puede moverlo.",
        it="Pelmet può nascondere %@, ma macOS lo tiene al suo posto, quindi l'editor non può spostarlo.",
        pt="O Pelmet pode ocultar %@, mas o macOS o mantém no lugar, então o editor não consegue movê-lo.",
        ja="Pelmetは%@を隠せますが、macOSがその位置を固定しているため、エディタでは移動できません。",
        zh="Pelmet 可以隐藏 %@，但 macOS 会将它固定在原位，因此编辑器无法移动它。",
        ko="Pelmet은 %@을(를) 숨길 수 있지만 macOS가 제자리에 고정하므로 편집기에서 옮길 수 없습니다.",
        ru="Pelmet может скрыть %@, но macOS держит её на своём месте, поэтому редактор не может её переместить.",
    ),
    "Time Machine": dict(de="Time Machine", fr="Time Machine", es="Time Machine", it="Time Machine", pt="Time Machine", ja="Time Machine", zh="时间机器", ko="Time Machine", ru="Time Machine"),
    "Stays where its app put it": dict(de="Bleibt, wo seine App es hingesetzt hat", fr="Reste là où son app l'a mis", es="Se queda donde su app lo puso", it="Resta dove la sua app l'ha messa", pt="Fica onde o app a colocou", ja="アプリが置いた場所に留まります", zh="留在其应用放置的位置", ko="앱이 놓은 자리에 그대로 있습니다", ru="Остаётся там, куда её поставило приложение"),
    "%@ ignores the moves Pelmet makes in the bar, so it keeps its own spot. Hold ⌘ and drag it yourself, or give it a launcher.": dict(
        de="%@ ignoriert die Verschiebungen, die Pelmet in der Leiste macht, und behält seinen Platz. Halte ⌘ und zieh es selbst, oder gib ihm einen Starter.",
        fr="%@ ignore les déplacements que Pelmet fait dans la barre et garde sa place. Maintiens ⌘ et déplace-le toi-même, ou donne-lui un lanceur.",
        es="%@ ignora los movimientos que Pelmet hace en la barra y conserva su sitio. Mantén ⌘ y arrástralo tú mismo, o dale un lanzador.",
        it="%@ ignora gli spostamenti che Pelmet fa nella barra e tiene il suo posto. Tieni premuto ⌘ e trascinala tu, oppure dalle un avvio app.",
        pt="%@ ignora os movimentos que o Pelmet faz na barra e mantém o seu lugar. Segure ⌘ e arraste você mesmo, ou dê a ele um atalho.",
        ja="%@はPelmetがバーで行う移動を無視し、自分の位置を保ちます。⌘を押しながら自分でドラッグするか、ランチャーを追加してください。",
        zh="%@ 会忽略 Pelmet 在菜单栏中的移动，保持自己的位置。按住 ⌘ 自行拖动，或为它添加一个启动器。",
        ko="%@은(는) Pelmet이 막대에서 하는 이동을 무시하고 제자리를 지킵니다. ⌘를 누른 채 직접 드래그하거나 실행기를 추가하세요.",
        ru="%@ игнорирует перемещения, которые Pelmet делает в строке меню, и остаётся на своём месте. Удерживайте ⌘ и перетащите её сами или добавьте для неё запуск.",
    ),
    "Incompatible app": dict(de="Inkompatible App", fr="App incompatible", es="App incompatible", it="App incompatibile", pt="App incompatível", ja="非対応のアプリ", zh="不兼容的应用", ko="호환되지 않는 앱", ru="Несовместимое приложение"),
    "%@ runs its menu bar icon from a helper macOS doesn't count as an app, so it won't show.": dict(de="%@ betreibt sein Menüleistensymbol über einen Helfer, den macOS nicht als App zählt — es wird daher nicht angezeigt.", fr="%@ fait tourner son icône de barre des menus via un assistant que macOS ne considère pas comme une app, donc elle ne s’affiche pas.", es="%@ ejecuta su icono de la barra de menús desde un ayudante que macOS no cuenta como app, así que no se muestra.", it="%@ gestisce l’icona della barra dei menu tramite un helper che macOS non considera un’app, quindi non compare.", pt="%@ executa o ícone da barra de menus por um auxiliar que o macOS não considera um app, então ele não aparece.", ja="%@ はmacOSがアプリと見なさないヘルパーでメニューバーのアイコンを表示しているため、表示されません。", zh="%@ 通过一个 macOS 不视为应用的辅助程序运行其菜单栏图标，所以不会显示。", ko="%@이(가) macOS가 앱으로 치지 않는 헬퍼로 메뉴 막대 아이콘을 실행하므로 표시되지 않습니다.", ru="%@ запускает свой значок в строке меню через помощник, который macOS не считает приложением, поэтому он не показывается."),
    "Menu bar icon": dict(de="Menüleistensymbol", fr="Icône de la barre des menus", es="Icono de la barra de menús", it="Icona della barra dei menu", pt="Ícone da barra de menus", ja="メニューバーのアイコン", zh="菜单栏图标", ko="메뉴 막대 아이콘", ru="Значок в строке меню"),
    "App icon": dict(de="App-Symbol", fr="Icône de l’app", es="Icono de la app", it="Icona dell’app", pt="Ícone do app", ja="アプリのアイコン", zh="应用图标", ko="앱 아이콘", ru="Значок приложения"),
    "No icons match": dict(de="Keine passenden Symbole", fr="Aucune icône ne correspond", es="Ningún icono coincide", it="Nessuna icona corrispondente", pt="Nenhum ícone corresponde", ja="一致するアイコンがありません", zh="没有匹配的图标", ko="일치하는 아이콘이 없습니다", ru="Нет подходящих значков"),
    "Pelmet's own system extras — they hide like any icon": dict(de="Pelmets eigene Systemextras — sie lassen sich wie jedes Symbol ausblenden", fr="Les extras système version Pelmet — ils se masquent comme toute icône", es="Los extras del sistema al estilo Pelmet — se ocultan como cualquier icono", it="Gli extra di sistema in versione Pelmet — si nascondono come ogni icona", pt="Os extras do sistema na versão do Pelmet — ocultam-se como qualquer ícone", ja="Pelmet版のシステム項目 — ほかのアイコンと同じように隠せます", zh="Pelmet 版的系统附加项 — 像任何图标一样隐藏", ko="Pelmet이 만든 시스템 항목 — 다른 아이콘처럼 숨겨집니다", ru="Системные элементы от Pelmet — скрываются, как любой значок"),
    "A Pelmet icon that opens an app — hides like any icon": dict(de="Ein Pelmet-Symbol, das eine App öffnet — lässt sich wie jedes Symbol ausblenden", fr="Une icône Pelmet qui ouvre une app — se masque comme toute icône", es="Un icono de Pelmet que abre una app — se oculta como cualquier icono", it="Un’icona Pelmet che apre un’app — si nasconde come ogni icona", pt="Um ícone do Pelmet que abre um app — oculta-se como qualquer ícone", ja="アプリを開くPelmetのアイコン — ほかのアイコンと同じように隠せます", zh="打开应用的 Pelmet 图标 — 像任何图标一样隐藏", ko="앱을 여는 Pelmet 아이콘 — 다른 아이콘처럼 숨겨집니다", ru="Значок Pelmet, открывающий приложение — скрывается, как любой значок"),
    "Click to play or pause, right-click for tracks.": dict(de="Klick spielt oder pausiert, Rechtsklick wechselt den Titel.", fr="Clic pour lire ou mettre en pause, clic droit pour changer de piste.", es="Clic para reproducir o pausar, clic derecho para cambiar de pista.", it="Clic per riprodurre o mettere in pausa, clic destro per cambiare brano.", pt="Clique para tocar ou pausar, clique direito para trocar de faixa.", ja="クリックで再生／一時停止、右クリックで曲送り。", zh="点按播放或暂停，右键切换曲目。", ko="클릭하면 재생/일시 정지, 오른쪽 클릭으로 트랙 이동.", ru="Щелчок — пуск или пауза, правый щелчок — смена трека."),
    "Appears while a camera or mic is live.": dict(de="Erscheint, solange Kamera oder Mikrofon aktiv sind.", fr="Apparaît quand la caméra ou le micro est actif.", es="Aparece mientras la cámara o el micrófono están activos.", it="Appare mentre fotocamera o microfono sono attivi.", pt="Aparece enquanto a câmera ou o microfone está ativo.", ja="カメラやマイクの使用中に表示。", zh="摄像头或麦克风工作时显示。", ko="카메라나 마이크가 켜져 있을 때 표시됩니다.", ru="Появляется, пока активны камера или микрофон."),
    "Opens AirDrop in Finder.": dict(de="Öffnet AirDrop im Finder.", fr="Ouvre AirDrop dans le Finder.", es="Abre AirDrop en el Finder.", it="Apre AirDrop nel Finder.", pt="Abre o AirDrop no Finder.", ja="FinderでAirDropを開きます。", zh="在访达中打开隔空投送。", ko="Finder에서 AirDrop을 엽니다.", ru="Открывает AirDrop в Finder."),
    "Runs the shortcut.": dict(de="Führt den Kurzbefehl aus.", fr="Exécute le raccourci.", es="Ejecuta el atajo.", it="Esegue il comando rapido.", pt="Executa o atalho.", ja="ショートカットを実行します。", zh="运行快捷指令。", ko="단축어를 실행합니다.", ru="Запускает быструю команду."),
    "Dividers for the bar — ⌘-drag them anywhere": dict(de="Trenner für die Leiste — mit ⌘ überallhin ziehen", fr="Des séparateurs pour la barre — ⌘-glissez-les où vous voulez", es="Divisores para la barra — arrástralos con ⌘ a cualquier sitio", it="Divisori per la barra — trascinali con ⌘ dove vuoi", pt="Divisores para a barra — arraste-os com ⌘ para onde quiser", ja="バー用の区切り — ⌘を押しながらどこへでもドラッグ", zh="菜单栏分隔线 — 按住 ⌘ 拖到任意位置", ko="막대용 구분선 — ⌘를 누른 채 어디로든 드래그", ru="Разделители для строки — перетаскивайте с ⌘ куда угодно"),
    "Search from %@ icons": dict(de="Aus %@ Symbolen suchen", fr="Rechercher parmi %@ icônes", es="Buscar entre %@ iconos", it="Cerca tra %@ icone", pt="Buscar entre %@ ícones", ja="%@ 個のアイコンから検索", zh="从 %@ 个图标中搜索", ko="%@개의 아이콘에서 검색", ru="Поиск среди %@ значков"),
    "Change icon": dict(de="Symbol ändern", fr="Changer l’icône", es="Cambiar icono", it="Cambia icona", pt="Alterar ícone", ja="アイコンを変更", zh="更改图标", ko="아이콘 변경", ru="Изменить значок"),
    "Active applications": dict(de="Aktive Apps", fr="Applications actives", es="Aplicaciones activas", it="Applicazioni attive", pt="Aplicativos ativos", ja="実行中のアプリケーション", zh="活跃的应用程序", ko="실행 중인 응용 프로그램", ru="Активные приложения"),
    "App launchers": dict(de="App-Starter", fr="Lanceurs d’apps", es="Lanzadores de apps", it="Avvio app", pt="Atalhos de apps", ja="アプリランチャー", zh="应用启动器", ko="앱 실행기", ru="Запуск приложений"),
    "Add a new app launcher": dict(de="Neuen App-Starter hinzufügen", fr="Ajouter un lanceur d’app", es="Añadir un lanzador de app", it="Aggiungi un avvio app", pt="Adicionar um atalho de app", ja="アプリランチャーを追加", zh="添加应用启动器", ko="앱 실행기 추가", ru="Добавить запуск приложения"),
    "Always shows": dict(de="Immer sichtbar", fr="Toujours visible", es="Siempre visible", it="Sempre visibile", pt="Sempre visível", ja="常に表示", zh="始终显示", ko="항상 표시", ru="Всегда виден"),
    "When active": dict(de="Bei Aktivität", fr="Si actif", es="Cuando está activo", it="Quando è attivo", pt="Quando ativo", ja="アクティブ時のみ", zh="活动时", ko="활성 상태일 때", ru="При активности"),
    "Always": dict(de="Immer", fr="Toujours", es="Siempre", it="Sempre", pt="Sempre", ja="常に", zh="始终", ko="항상", ru="Всегда"),
    "Only while app is running": dict(de="Nur wenn die App läuft", fr="Seulement si l’app est ouverte", es="Solo si la app está abierta", it="Solo se l’app è in esecuzione", pt="Só com o app aberto", ja="アプリの実行中のみ", zh="仅在应用运行时", ko="앱 실행 중에만", ru="Только когда приложение запущено"),
    "Incompatible app not showing up in the menu bar? Add an app launcher.": dict(de="Inkompatible App taucht nicht in der Menüleiste auf? Füge einen App-Starter hinzu.", fr="Une app incompatible n’apparaît pas dans la barre des menus ? Ajoutez un lanceur d’app.", es="¿Una app incompatible no aparece en la barra de menús? Añade un lanzador de app.", it="Un’app incompatibile non compare nella barra dei menu? Aggiungi un avvio app.", pt="Um app incompatível não aparece na barra de menus? Adicione um atalho de app.", ja="非対応のアプリがメニューバーに出てきませんか？アプリランチャーを追加しましょう。", zh="不兼容的应用没有出现在菜单栏？添加一个应用启动器。", ko="호환되지 않는 앱이 메뉴 막대에 나타나지 않나요? 앱 실행기를 추가하세요.", ru="Несовместимое приложение не появляется в строке меню? Добавьте запуск приложения."),
    "Pelmet app launcher — click opens the app; hides like any Pelmet item": dict(de="Pelmet-App-Starter — Klick öffnet die App; lässt sich wie jedes Pelmet-Element ausblenden", fr="Lanceur d’app Pelmet — un clic ouvre l’app ; se masque comme tout élément Pelmet", es="Lanzador de app de Pelmet — un clic abre la app; se oculta como cualquier elemento de Pelmet", it="Avvio app Pelmet — un clic apre l’app; si nasconde come ogni elemento Pelmet", pt="Atalho de app do Pelmet — um clique abre o app; oculta-se como qualquer item do Pelmet", ja="Pelmetのアプリランチャー — クリックでアプリを開きます。ほかのPelmet項目と同じように隠せます", zh="Pelmet 应用启动器 — 点击打开应用；可像任何 Pelmet 项目一样隐藏", ko="Pelmet 앱 실행기 — 클릭하면 앱이 열립니다. 다른 Pelmet 항목처럼 숨겨집니다", ru="Запуск приложения Pelmet — клик открывает приложение; скрывается, как любой элемент Pelmet"),
    "Launcher added — now turn this icon off in %@'s settings": dict(de="Starter hinzugefügt — schalte dieses Symbol jetzt in den Einstellungen von %@ aus", fr="Lanceur ajouté — désactivez maintenant cette icône dans les réglages de %@", es="Lanzador añadido — ahora desactiva este icono en los ajustes de %@", it="Avvio app aggiunto — ora disattiva questa icona nelle impostazioni di %@", pt="Atalho adicionado — agora desative este ícone nos ajustes de %@", ja="ランチャーを追加しました — 次に %@ の設定でこのアイコンをオフにしてください", zh="已添加启动器 — 现在请在 %@ 的设置中关闭此图标", ko="실행기를 추가했습니다 — 이제 %@ 설정에서 이 아이콘을 끄세요", ru="Запуск добавлен — теперь отключите этот значок в настройках %@"),
    "Add a launcher for %@": dict(de="Starter für %@ hinzufügen", fr="Ajouter un lanceur pour %@", es="Añadir un lanzador para %@", it="Aggiungi un avvio per %@", pt="Adicionar um atalho para %@", ja="%@ のランチャーを追加", zh="为 %@ 添加启动器", ko="%@ 실행기 추가", ru="Добавить запуск для %@"),
    "Its launcher is ready": dict(de="Der Starter ist bereit", fr="Son lanceur est prêt", es="Su lanzador está listo", it="Il suo avvio app è pronto", pt="O atalho está pronto", ja="ランチャーの準備ができました", zh="启动器已就绪", ko="실행기가 준비되었습니다", ru="Запуск готов"),
    "Turn this icon off in %@'s settings. The launcher takes over from there.": dict(de="Schalte dieses Symbol in den Einstellungen von %@ aus. Ab dann übernimmt der Starter.", fr="Désactivez cette icône dans les réglages de %@. Le lanceur prend le relais.", es="Desactiva este icono en los ajustes de %@. A partir de ahí, el lanzador se encarga.", it="Disattiva questa icona nelle impostazioni di %@. Da lì in poi ci pensa l’avvio app.", pt="Desative este ícone nos ajustes de %@. A partir daí, o atalho assume.", ja="%@ の設定でこのアイコンをオフにしてください。あとはランチャーが引き継ぎます。", zh="在 %@ 的设置中关闭此图标。之后由启动器接管。", ko="%@ 설정에서 이 아이콘을 끄세요. 그 뒤로는 실행기가 맡습니다.", ru="Отключите этот значок в настройках %@. Дальше всё возьмёт на себя запуск приложения."),
    "An app launcher fixes that: a Pelmet icon that opens %@ and works like any other menu bar item.": dict(de="Ein App-Starter löst das: ein Pelmet-Symbol, das %@ öffnet und sich wie jedes andere Menüleistenelement verhält.", fr="Un lanceur d’app règle ça : une icône Pelmet qui ouvre %@ et se comporte comme n’importe quel autre élément de la barre des menus.", es="Un lanzador de app lo arregla: un icono de Pelmet que abre %@ y funciona como cualquier otro elemento de la barra de menús.", it="Un avvio app risolve: un’icona Pelmet che apre %@ e funziona come qualsiasi altro elemento della barra dei menu.", pt="Um atalho de app resolve: um ícone do Pelmet que abre %@ e funciona como qualquer outro item da barra de menus.", ja="アプリランチャーで解決できます。%@ を開くPelmetのアイコンで、ほかのメニューバー項目と同じように使えます。", zh="应用启动器可以解决：一个能打开 %@ 的 Pelmet 图标，像其他菜单栏项目一样工作。", ko="앱 실행기가 해결합니다. %@을(를) 여는 Pelmet 아이콘으로, 다른 메뉴 막대 항목처럼 작동합니다.", ru="Запуск приложения это решает: значок Pelmet, который открывает %@ и работает, как любой другой элемент строки меню."),
    "Add a launcher": dict(de="Starter hinzufügen", fr="Ajouter un lanceur", es="Añadir un lanzador", it="Aggiungi un avvio app", pt="Adicionar um atalho", ja="ランチャーを追加", zh="添加启动器", ko="실행기 추가", ru="Добавить запуск"),
    "Choose an app to launch": dict(de="App zum Öffnen auswählen", fr="Choisissez l’app à ouvrir", es="Elige la app que quieres abrir", it="Scegli l’app da aprire", pt="Escolha o app a abrir", ja="開くアプリを選択", zh="选择要打开的应用", ko="열 앱 선택", ru="Выберите приложение для запуска"),
    "Quit %@": dict(de="%@ beenden", fr="Quitter %@", es="Salir de %@", it="Esci da %@", pt="Encerrar %@", ja="%@ を終了", zh="退出 %@", ko="%@ 종료", ru="Завершить %@"),
    "Keyboard shortcut": dict(de="Tastenkürzel", fr="Raccourci clavier", es="Atajo de teclado", it="Scorciatoia da tastiera", pt="Atalho de teclado", ja="キーボードショートカット", zh="键盘快捷键", ko="키보드 단축키", ru="Сочетание клавиш"),
    "Toggles the hidden icons from anywhere.": dict(de="Blendet die ausgeblendeten Symbole von überall ein und aus.", fr="Affiche ou masque les icônes cachées depuis n’importe où.", es="Muestra u oculta los iconos ocultos desde cualquier app.", it="Mostra o nasconde le icone nascoste da qualsiasi app.", pt="Mostra ou oculta os ícones ocultos de qualquer app.", ja="どこからでも隠したアイコンを切り替えます。", zh="在任何地方切换隐藏的图标。", ko="어디서든 숨긴 아이콘을 전환합니다.", ru="Показывает и скрывает спрятанные значки из любого приложения."),
    "Held by another app — record a different one.": dict(de="Wird von einer anderen App belegt — nimm ein anderes auf.", fr="Déjà pris par une autre app — enregistrez-en un autre.", es="Otra app ya lo usa — graba uno distinto.", it="Già usata da un’altra app — registrane un’altra.", pt="Outro app já o usa — grave um diferente.", ja="ほかのアプリが使用中です。別のショートカットを記録してください。", zh="已被其他应用占用，请录制另一个。", ko="다른 앱이 사용 중입니다. 다른 단축키를 기록하세요.", ru="Занято другим приложением — запишите другое."),
    "Record shortcut": dict(de="Kürzel aufnehmen", fr="Enregistrer un raccourci", es="Grabar atajo", it="Registra scorciatoia", pt="Gravar atalho", ja="ショートカットを記録", zh="录制快捷键", ko="단축키 기록", ru="Записать сочетание"),
    "Type shortcut…": dict(de="Kürzel drücken…", fr="Tapez le raccourci…", es="Pulsa el atajo…", it="Premi la scorciatoia…", pt="Digite o atalho…", ja="ショートカットを押してください…", zh="按下快捷键…", ko="단축키를 누르세요…", ru="Нажмите сочетание…"),
    "Click, then press the new shortcut. ⎋ cancels, ⌫ restores %@.": dict(de="Klicken, dann das neue Kürzel drücken. ⎋ bricht ab, ⌫ stellt %@ wieder her.", fr="Cliquez, puis tapez le nouveau raccourci. ⎋ annule, ⌫ rétablit %@.", es="Haz clic y pulsa el nuevo atajo. ⎋ cancela, ⌫ restaura %@.", it="Fai clic, poi premi la nuova scorciatoia. ⎋ annulla, ⌫ ripristina %@.", pt="Clique e pressione o novo atalho. ⎋ cancela, ⌫ restaura %@.", ja="クリックしてから新しいショートカットを押します。⎋ でキャンセル、⌫ で %@ に戻します。", zh="点击后按下新快捷键。⎋ 取消，⌫ 恢复为 %@。", ko="클릭한 뒤 새 단축키를 누르세요. ⎋ 취소, ⌫ 는 %@ 로 되돌립니다.", ru="Нажмите, затем введите новое сочетание. ⎋ отменяет, ⌫ возвращает %@."),
    "Restore %@": dict(de="%@ wiederherstellen", fr="Rétablir %@", es="Restaurar %@", it="Ripristina %@", pt="Restaurar %@", ja="%@ に戻す", zh="恢复为 %@", ko="%@ 로 되돌리기", ru="Вернуть %@"),
    "Open Settings": dict(de="Einstellungen öffnen", fr="Ouvrir les réglages", es="Abrir ajustes", it="Apri impostazioni", pt="Abrir ajustes", ja="設定を開く", zh="打开设置", ko="설정 열기", ru="Открыть настройки"),
    "Opens Pelmet Settings from anywhere.": dict(de="Öffnet die Pelmet-Einstellungen von überall.", fr="Ouvre les réglages de Pelmet depuis n’importe où.", es="Abre los ajustes de Pelmet desde cualquier app.", it="Apre le impostazioni di Pelmet da qualsiasi app.", pt="Abre os ajustes do Pelmet de qualquer app.", ja="どこからでもPelmet設定を開きます。", zh="在任何地方打开 Pelmet 设置。", ko="어디서든 Pelmet 설정을 엽니다.", ru="Открывает настройки Pelmet из любого приложения."),
    # Pelmet timer + fast user switching (2026-09-15)
    "Timer": dict(de="Timer", fr="Minuteur", es="Temporizador", it="Timer", pt="Timer", ja="タイマー", zh="计时器", ko="타이머", ru="Таймер"),
    "Users": dict(de="Benutzer", fr="Utilisateurs", es="Usuarios", it="Utenti", pt="Usuários", ja="ユーザ", zh="用户", ko="사용자", ru="Пользователи"),
    "Fast user switching": dict(de="Schneller Benutzerwechsel", fr="Changement rapide d’utilisateur", es="Cambio rápido de usuario", it="Cambio utente rapido", pt="Troca rápida de usuário", ja="ファストユーザスイッチ", zh="快速用户切换", ko="빠른 사용자 전환", ru="Быстрое переключение пользователей"),
    "A countdown that stays in the bar. Click for durations, rings when it ends.": dict(de="Ein Countdown, der in der Leiste bleibt. Klicken für Dauern, klingelt am Ende.", fr="Un compte à rebours qui reste dans la barre. Cliquez pour choisir la durée, il sonne à la fin.", es="Una cuenta atrás que se queda en la barra. Haz clic para elegir la duración, suena al terminar.", it="Un conto alla rovescia che resta nella barra. Clic per la durata, suona alla fine.", pt="Uma contagem regressiva que fica na barra. Clique para escolher a duração, toca ao terminar.", ja="バーに残るカウントダウン。クリックで時間を選び、終了時に鳴ります。", zh="留在菜单栏中的倒计时。点击选择时长，结束时响铃。", ko="메뉴 막대에 남아 있는 카운트다운. 클릭해 시간을 고르면 끝날 때 울립니다.", ru="Обратный отсчёт, который остаётся в строке меню. Нажмите, чтобы выбрать время, по окончании прозвенит."),
    "Other users, the login window, lock screen.": dict(de="Andere Benutzer, Anmeldefenster, Bildschirm sperren.", fr="Autres utilisateurs, fenêtre de connexion, verrouillage de l’écran.", es="Otros usuarios, la ventana de inicio de sesión, bloquear pantalla.", it="Altri utenti, finestra di login, blocco schermo.", pt="Outros usuários, a janela de login, bloquear tela.", ja="ほかのユーザ、ログインウインドウ、画面ロック。", zh="其他用户、登录窗口、锁定屏幕。", ko="다른 사용자, 로그인 윈도우, 화면 잠금.", ru="Другие пользователи, окно входа, блокировка экрана."),
    "%lld min": dict(de="%lld Min.", fr="%lld min", es="%lld min", it="%lld min", pt="%lld min", ja="%lld分", zh="%lld 分钟", ko="%lld분", ru="%lld мин"),
    "1 hour": dict(de="1 Stunde", fr="1 heure", es="1 hora", it="1 ora", pt="1 hora", ja="1時間", zh="1 小时", ko="1시간", ru="1 час"),
    "%lld hours": dict(de="%lld Stunden", fr="%lld heures", es="%lld horas", it="%lld ore", pt="%lld horas", ja="%lld時間", zh="%lld 小时", ko="%lld시간", ru="%lld ч"),
    "Custom…": dict(de="Eigene…", fr="Personnalisé…", es="Personalizado…", it="Personalizzato…", pt="Personalizado…", ja="カスタム…", zh="自定…", ko="사용자 설정…", ru="Другое…"),
    "Minutes": dict(de="Minuten", fr="Minutes", es="Minutos", it="Minuti", pt="Minutos", ja="分", zh="分钟", ko="분", ru="Минуты"),
    "Start": dict(de="Starten", fr="Démarrer", es="Iniciar", it="Avvia", pt="Iniciar", ja="開始", zh="开始", ko="시작", ru="Начать"),
    "Cancel": dict(de="Abbrechen", fr="Annuler", es="Cancelar", it="Annulla", pt="Cancelar", ja="キャンセル", zh="取消", ko="취소", ru="Отменить"),
    "%@ left": dict(de="Noch %@", fr="%@ restantes", es="Quedan %@", it="Mancano %@", pt="Faltam %@", ja="残り %@", zh="剩余 %@", ko="%@ 남음", ru="Осталось %@"),
    "Pause": dict(de="Anhalten", fr="Pause", es="Pausar", it="Pausa", pt="Pausar", ja="一時停止", zh="暂停", ko="일시 정지", ru="Пауза"),
    "Resume": dict(de="Fortsetzen", fr="Reprendre", es="Reanudar", it="Riprendi", pt="Retomar", ja="再開", zh="继续", ko="재개", ru="Продолжить"),
    "Add a minute": dict(de="Eine Minute hinzufügen", fr="Ajouter une minute", es="Añadir un minuto", it="Aggiungi un minuto", pt="Adicionar um minuto", ja="1分追加", zh="加一分钟", ko="1분 추가", ru="Добавить минуту"),
    "Cancel timer": dict(de="Timer abbrechen", fr="Annuler le minuteur", es="Cancelar temporizador", it="Annulla timer", pt="Cancelar timer", ja="タイマーをキャンセル", zh="取消计时器", ko="타이머 취소", ru="Отменить таймер"),
    "Dismiss": dict(de="Ausblenden", fr="Ignorer", es="Descartar", it="Ignora", pt="Dispensar", ja="閉じる", zh="关闭", ko="닫기", ru="Закрыть"),
    "Timer done": dict(de="Timer abgelaufen", fr="Minuteur terminé", es="Temporizador terminado", it="Timer terminato", pt="Timer concluído", ja="タイマー終了", zh="计时器结束", ko="타이머 종료", ru="Таймер завершён"),
    "Click the timer in the menu bar to dismiss it.": dict(de="Klicke auf den Timer in der Menüleiste, um ihn auszublenden.", fr="Cliquez sur le minuteur dans la barre des menus pour l’ignorer.", es="Haz clic en el temporizador de la barra de menús para descartarlo.", it="Fai clic sul timer nella barra dei menu per ignorarlo.", pt="Clique no timer na barra de menus para dispensá-lo.", ja="メニューバーのタイマーをクリックして閉じます。", zh="点击菜单栏中的计时器以关闭。", ko="메뉴 막대의 타이머를 클릭해 닫으세요.", ru="Нажмите на таймер в строке меню, чтобы закрыть его."),
    "Login Window…": dict(de="Anmeldefenster…", fr="Fenêtre de connexion…", es="Ventana de inicio de sesión…", it="Finestra di login…", pt="Janela de login…", ja="ログインウインドウ…", zh="登录窗口…", ko="로그인 윈도우…", ru="Окно входа…"),
    "Lock Screen": dict(de="Bildschirm sperren", fr="Verrouiller l’écran", es="Bloquear pantalla", it="Blocca schermo", pt="Bloquear tela", ja="画面をロック", zh="锁定屏幕", ko="화면 잠금", ru="Заблокировать экран"),
    "Users & Groups Settings…": dict(de="Einstellungen „Benutzer & Gruppen“…", fr="Réglages Utilisateurs et groupes…", es="Ajustes de Usuarios y grupos…", it="Impostazioni Utenti e gruppi…", pt="Ajustes de Usuários e Grupos…", ja="「ユーザとグループ」設定…", zh="“用户与群组”设置…", ko="사용자 및 그룹 설정…", ru="Настройки «Пользователи и группы»…"),
    # ── Time Machine & Siri items ───────────────────────────────────
    "Time Machine": dict(de="Time Machine", fr="Time Machine", es="Time Machine", it="Time Machine", pt="Time Machine", ja="Time Machine", zh="时间机器", ko="Time Machine", ru="Time Machine"),
    "Siri": dict(de="Siri", fr="Siri", es="Siri", it="Siri", pt="Siri", ja="Siri", zh="Siri", ko="Siri", ru="Siri"),
    "Latest backup, Back Up Now. Apple's own icon turns off in System Settings while this is on.": dict(
        de="Letztes Backup, Backup jetzt erstellen. Apples eigenes Symbol wird in den Systemeinstellungen ausgeschaltet, solange dies aktiv ist.",
        fr="Dernière sauvegarde, Sauvegarder maintenant. L’icône d’Apple est désactivée dans Réglages Système tant que ceci est activé.",
        es="Última copia, Realizar copia ahora. El icono de Apple se desactiva en Ajustes del Sistema mientras esto esté activado.",
        it="Ultimo backup, Esegui backup adesso. L’icona di Apple viene disattivata nelle Impostazioni di Sistema finché questo è attivo.",
        pt="Último backup, Fazer Backup Agora. O ícone da Apple é desativado nos Ajustes do Sistema enquanto isto estiver ativado.",
        ja="最新のバックアップと今すぐバックアップ。オンの間、Appleのアイコンはシステム設定でオフになります。",
        zh="最近备份、立即备份。开启期间，Apple 自带的图标会在系统设置中关闭。",
        ko="최근 백업, 지금 백업. 켜져 있는 동안 Apple의 아이콘은 시스템 설정에서 꺼집니다.",
        ru="Последняя копия, Создать копию сейчас. Пока это включено, значок Apple отключается в Системных настройках.",
    ),
    "Opens Siri. Apple's own icon turns off in System Settings while this is on.": dict(
        de="Öffnet Siri. Apples eigenes Symbol wird in den Systemeinstellungen ausgeschaltet, solange dies aktiv ist.",
        fr="Ouvre Siri. L’icône d’Apple est désactivée dans Réglages Système tant que ceci est activé.",
        es="Abre Siri. El icono de Apple se desactiva en Ajustes del Sistema mientras esto esté activado.",
        it="Apre Siri. L’icona di Apple viene disattivata nelle Impostazioni di Sistema finché questo è attivo.",
        pt="Abre a Siri. O ícone da Apple é desativado nos Ajustes do Sistema enquanto isto estiver ativado.",
        ja="Siriを開きます。オンの間、Appleのアイコンはシステム設定でオフになります。",
        zh="打开 Siri。开启期间，Apple 自带的图标会在系统设置中关闭。",
        ko="Siri를 엽니다. 켜져 있는 동안 Apple의 아이콘은 시스템 설정에서 꺼집니다.",
        ru="Открывает Siri. Пока это включено, значок Apple отключается в Системных настройках.",
    ),
    # Apple's own wording for the verbs (TimeMachine.menu's strings table).
    "Back Up Now": dict(de="Backup jetzt erstellen", fr="Sauvegarder maintenant", es="Realizar copia de seguridad ahora", it="Esegui backup adesso", pt="Fazer Backup Agora", ja="今すぐバックアップを作成", zh="立即备份", ko="지금 백업", ru="Создать резервную копию сейчас"),
    "Skip This Backup": dict(de="Dieses Backup überspringen", fr="Ignorer cette sauvegarde", es="Omitir esta copia de seguridad", it="Ignora questo backup", pt="Ignorar Este Backup", ja="このバックアップ作成をスキップ", zh="跳过此备份", ko="이 백업 건너뛰기", ru="Пропустить эту копию"),
    "Browse Time Machine Backups": dict(de="Time Machine-Backups durchsuchen", fr="Parcourir les sauvegardes Time Machine", es="Explorar copias de seguridad de Time Machine", it="Sfoglia i backup di Time Machine", pt="Explorar Backups do Time Machine", ja="Time Machineバックアップをブラウズ", zh="浏览时间机器备份", ko="Time Machine 백업 탐색", ru="Просмотреть резервные копии Time Machine"),
    "Open Time Machine Settings…": dict(de="Time Machine-Einstellungen öffnen …", fr="Ouvrir les réglages Time Machine…", es="Abrir los ajustes de Time Machine…", it="Apri le impostazioni di Time Machine…", pt="Abrir Ajustes do Time Machine…", ja="Time Machine設定を開く…", zh="打开时间机器设置…", ko="Time Machine 설정 열기…", ru="Открыть настройки Time Machine…"),
    "Waiting to Complete First Backup": dict(de="Auf Fertigstellen des ersten Backup warten", fr="En attente de la fin de la première sauvegarde", es="Esperando para completar la primera copia de seguridad", it="In attesa del completamento del primo backup", pt="Esperando que o Primeiro Backup Termine", ja="初回バックアップ完了を待機中", zh="正在等待完成第一次备份", ko="첫 번째 백업 완료 기다리는 중", ru="Ожидание окончания создания первой резервной копии"),
    "Latest Backup to “%@”": dict(de="Letztes Backup auf „%@“", fr="Dernière sauvegarde sur « %@ »", es="Última copia de seguridad en “%@”", it="Ultimo backup su “%@”", pt="Último Backup em “%@”", ja="最新のバックアップ先：“%@”", zh="最近备份至“%@”", ko="“%@”에 최근 백업", ru="Последняя копия на «%@»"),
    "Backing Up: %lld%%": dict(de="Backup erstellen: %lld %%", fr="Sauvegarde en cours : %lld %%", es="Realizando copia: %lld %%", it="Backup in corso: %lld%%", pt="Fazendo Backup: %lld%%", ja="バックアップ中: %lld%%", zh="正在备份：%lld%%", ko="백업 중: %lld%%", ru="Создается копия: %lld %%"),
    "Preparing Backup…": dict(de="Backup wird vorbereitet …", fr="Préparation de la sauvegarde…", es="Preparando la copia de seguridad…", it="Preparazione del backup…", pt="Preparando o Backup…", ja="バックアップを準備中…", zh="正在准备备份…", ko="백업 준비 중…", ru="Подготовка резервной копии…"),
    "Finishing Backup…": dict(de="Backup wird abgeschlossen …", fr="Finalisation de la sauvegarde…", es="Finalizando la copia de seguridad…", it="Completamento del backup…", pt="Concluindo o Backup…", ja="バックアップを完了中…", zh="正在完成备份…", ko="백업 마무리 중…", ru="Завершение резервной копии…"),
    "Stopping Backup…": dict(de="Backup wird gestoppt …", fr="Arrêt de la sauvegarde…", es="Deteniendo la copia de seguridad…", it="Interruzione del backup…", pt="Parando o Backup…", ja="バックアップを停止中…", zh="正在停止备份…", ko="백업 중단 중…", ru="Остановка резервной копии…"),
    "No Backup Disk Selected": dict(de="Kein Backup-Volume ausgewählt", fr="Aucun disque de sauvegarde sélectionné", es="No se ha seleccionado ningún disco de copia de seguridad", it="Nessun disco di backup selezionato", pt="Nenhum Disco de Backup Selecionado", ja="バックアップディスクが選択されていません", zh="未选择备份磁盘", ko="선택된 백업 디스크 없음", ru="Диск для резервных копий не выбран"),
    "Pinned by macOS — Pelmet can hide it, but not move it": dict(de="Von macOS fixiert – Pelmet kann es ausblenden, aber nicht bewegen", fr="Épinglé par macOS – Pelmet peut le masquer, mais pas le déplacer", es="Fijado por macOS: Pelmet puede ocultarlo, pero no moverlo", it="Bloccato da macOS: Pelmet può nasconderlo, ma non spostarlo", pt="Fixado pelo macOS — o Pelmet pode ocultá-lo, mas não movê-lo", ja="macOSが固定しています。Pelmetは非表示にできますが、移動はできません", zh="由 macOS 固定 — Pelmet 可以隐藏它，但无法移动", ko="macOS가 고정함 — Pelmet이 숨길 수는 있지만 옮길 수는 없습니다", ru="Закреплено macOS — Pelmet может скрыть, но не переместить"),
    "Use Pelmet's Siri": dict(de="Pelmets Siri verwenden", fr="Utiliser le Siri de Pelmet", es="Usar el Siri de Pelmet", it="Usa il Siri di Pelmet", pt="Usar a Siri do Pelmet", ja="PelmetのSiriを使う", zh="使用 Pelmet 的 Siri", ko="Pelmet의 Siri 사용", ru="Использовать Siri от Pelmet"),
    "Use Pelmet's Time Machine": dict(de="Pelmets Time Machine verwenden", fr="Utiliser le Time Machine de Pelmet", es="Usar el Time Machine de Pelmet", it="Usa il Time Machine di Pelmet", pt="Usar o Time Machine do Pelmet", ja="PelmetのTime Machineを使う", zh="使用 Pelmet 的时间机器", ko="Pelmet의 Time Machine 사용", ru="Использовать Time Machine от Pelmet"),
    "Siri is a locked macOS system icon. Turn on Pelmet's Siri below for an icon you can move.": dict(
        de="Siri ist ein gesperrtes macOS-Systemsymbol. Aktiviere unten Pelmets Siri für ein Symbol, das du bewegen kannst.",
        fr="Siri est une icône système verrouillée par macOS. Activez le Siri de Pelmet ci-dessous pour une icône que vous pouvez déplacer.",
        es="Siri es un icono del sistema bloqueado por macOS. Activa abajo el Siri de Pelmet para tener un icono que puedas mover.",
        it="Siri è un'icona di sistema bloccata da macOS. Attiva qui sotto il Siri di Pelmet per avere un'icona che puoi spostare.",
        pt="A Siri é um ícone de sistema bloqueado pelo macOS. Ative abaixo a Siri do Pelmet para ter um ícone que você pode mover.",
        ja="SiriはmacOSがロックしているシステムアイコンです。下でPelmetのSiriをオンにすると、移動できるアイコンになります。",
        zh="Siri 是被 macOS 锁定的系统图标。在下方开启 Pelmet 的 Siri，即可获得可移动的图标。",
        ko="Siri는 macOS가 잠근 시스템 아이콘입니다. 아래에서 Pelmet의 Siri를 켜면 옮길 수 있는 아이콘이 됩니다.",
        ru="Siri — системный значок, заблокированный macOS. Включите ниже Siri от Pelmet, чтобы получить значок, который можно перемещать.",
    ),
    "Time Machine is a locked macOS system icon. Turn on Pelmet's Time Machine below for an icon you can move.": dict(
        de="Time Machine ist ein gesperrtes macOS-Systemsymbol. Aktiviere unten Pelmets Time Machine für ein Symbol, das du bewegen kannst.",
        fr="Time Machine est une icône système verrouillée par macOS. Activez le Time Machine de Pelmet ci-dessous pour une icône que vous pouvez déplacer.",
        es="Time Machine es un icono del sistema bloqueado por macOS. Activa abajo el Time Machine de Pelmet para tener un icono que puedas mover.",
        it="Time Machine è un'icona di sistema bloccata da macOS. Attiva qui sotto il Time Machine di Pelmet per avere un'icona che puoi spostare.",
        pt="O Time Machine é um ícone de sistema bloqueado pelo macOS. Ative abaixo o Time Machine do Pelmet para ter um ícone que você pode mover.",
        ja="Time MachineはmacOSがロックしているシステムアイコンです。下でPelmetのTime Machineをオンにすると、移動できるアイコンになります。",
        zh="时间机器是被 macOS 锁定的系统图标。在下方开启 Pelmet 的时间机器，即可获得可移动的图标。",
        ko="Time Machine은 macOS가 잠근 시스템 아이콘입니다. 아래에서 Pelmet의 Time Machine을 켜면 옮길 수 있는 아이콘이 됩니다.",
        ru="Time Machine — системный значок, заблокированный macOS. Включите ниже Time Machine от Pelmet, чтобы получить значок, который можно перемещать.",
    ),
    "Use Pelmet's Siri and Time Machine": dict(de="Pelmets Siri und Time Machine verwenden", fr="Utiliser le Siri et le Time Machine de Pelmet", es="Usar el Siri y el Time Machine de Pelmet", it="Usa il Siri e il Time Machine di Pelmet", pt="Usar a Siri e o Time Machine do Pelmet", ja="PelmetのSiriとTime Machineを使う", zh="使用 Pelmet 的 Siri 和时间机器", ko="Pelmet의 Siri와 Time Machine 사용", ru="Использовать Siri и Time Machine от Pelmet"),
    "Siri and Time Machine are locked macOS system icons. Turn on Pelmet's Siri and Time Machine below for separate icons you can move.": dict(
        de="Siri und Time Machine sind gesperrte macOS-Systemsymbole. Aktiviere unten Pelmets Siri und Time Machine für einzelne Symbole, die du bewegen kannst.",
        fr="Siri et Time Machine sont des icônes système verrouillées par macOS. Activez le Siri et le Time Machine de Pelmet ci-dessous pour des icônes distinctes que vous pouvez déplacer.",
        es="Siri y Time Machine son iconos del sistema bloqueados por macOS. Activa abajo el Siri y el Time Machine de Pelmet para tener iconos separados que puedas mover.",
        it="Siri e Time Machine sono icone di sistema bloccate da macOS. Attiva qui sotto il Siri e il Time Machine di Pelmet per avere icone separate che puoi spostare.",
        pt="A Siri e o Time Machine são ícones de sistema bloqueados pelo macOS. Ative abaixo a Siri e o Time Machine do Pelmet para ter ícones separados que você pode mover.",
        ja="SiriとTime MachineはmacOSがロックしているシステムアイコンです。下でPelmetのSiriとTime Machineをオンにすると、個別に移動できるアイコンになります。",
        zh="Siri 和时间机器是被 macOS 锁定的系统图标。在下方开启 Pelmet 的 Siri 和时间机器，即可获得可单独移动的图标。",
        ko="Siri와 Time Machine은 macOS가 잠근 시스템 아이콘입니다. 아래에서 Pelmet의 Siri와 Time Machine을 켜면 따로 옮길 수 있는 아이콘이 됩니다.",
        ru="Siri и Time Machine — системные значки, заблокированные macOS. Включите ниже Siri и Time Machine от Pelmet, чтобы получить отдельные значки, которые можно перемещать.",
    ),
    "Backup Failed…": dict(de="Backup fehlgeschlagen …", fr="Échec de la sauvegarde…", es="Error en la copia de seguridad…", it="Backup non riuscito…", pt="Falha no Backup…", ja="バックアップに失敗しました…", zh="备份失败…", ko="백업 실패…", ru="Сбой резервного копирования…"),
    "Siri Settings…": dict(de="Siri-Einstellungen …", fr="Réglages Siri…", es="Ajustes de Siri…", it="Impostazioni Siri…", pt="Ajustes da Siri…", ja="Siri設定…", zh="Siri 设置…", ko="Siri 설정…", ru="Настройки Siri…"),
    "Focus": dict(de="Fokus", fr="Concentration", es="Modo de concentración", it="Full immersion", pt="Foco", ja="集中モード", zh="专注模式", ko="집중 모드", ru="Фокусирование"),
    "Shows which Focus is on. Click for the Focus panel.": dict(de="Zeigt, welcher Fokus aktiv ist. Klick öffnet das Fokus-Panel.", fr="Indique quelle Concentration est active. Un clic ouvre le panneau Concentration.", es="Muestra qué modo de concentración está activo. Un clic abre el panel.", it="Mostra quale Full immersion è attiva. Un clic apre il pannello.", pt="Mostra qual Foco está ativo. Clique para abrir o painel de Foco.", ja="オンになっている集中モードを表示します。クリックで集中モードパネルを開きます。", zh="显示当前开启的专注模式。点按打开专注模式面板。", ko="켜져 있는 집중 모드를 표시합니다. 클릭하면 집중 모드 패널이 열립니다.", ru="Показывает, какой режим фокусирования включён. Щелчок открывает панель."),
    "Focus Settings…": dict(de="Fokus-Einstellungen …", fr="Réglages de Concentration…", es="Ajustes de concentración…", it="Impostazioni Full immersion…", pt="Ajustes de Foco…", ja="集中モード設定…", zh="专注模式设置…", ko="집중 모드 설정…", ru="Настройки фокусирования…"),
}

LANG_CODES = {"de": "de", "fr": "fr", "es": "es", "it": "it", "pt": "pt-BR", "ja": "ja", "zh": "zh-Hans", "ko": "ko", "ru": "ru"}


def main() -> None:
    strings = {}
    for key, langs in T.items():
        missing = set(LANG_CODES) - set(langs)
        assert not missing, f"{key!r} missing {missing}"
        strings[key] = {
            "localizations": {
                LANG_CODES[code]: {"stringUnit": {"state": "translated", "value": value}}
                for code, value in langs.items()
            }
        }
    catalog = {"sourceLanguage": "en", "strings": strings, "version": "1.0"}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True) + "\n")
    print(f"{len(strings)} keys × {len(LANG_CODES)} languages → {OUT.relative_to(OUT.parents[2])}")


if __name__ == "__main__":
    main()
